#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from semantic_general_records import build_general_records
from semantic_intruder_help_records import build_intruder_help_records
from semantic_room_records import build_room_records
from semantic_event_records import (
    EVENT_RULE_IDS,
    build_event_records,
    build_event_source_index,
    event_source_registry_rows,
)
from semantic_exploration_records import (
    EXPLORATION_RULE_IDS,
    build_exploration_records,
    build_exploration_source_index,
    exploration_source_registry_rows,
)
from semantic_robot_records import (
    ROBOT_RULE_IDS,
    build_robot_records,
    build_robot_source_index,
    robot_source_registry_rows,
)
from semantic_attack_records import (
    ATTACK_QUESTION_BLOCKS,
    ATTACK_RULE_IDS,
    build_attack_records,
    build_attack_source_index,
    attack_source_registry_rows,
)
from room_icon_denotations import build_room_icon_denotations

REPO = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--output-dir', type=Path, default=REPO / 'docs/rules/semantics')
args = parser.parse_args()
OUT = args.output_dir.resolve()
OUT.mkdir(parents=True, exist_ok=True)


def sha(path: str) -> str:
    return hashlib.sha256((REPO / path).read_bytes()).hexdigest()


def write(name: str, value: dict) -> None:
    (OUT / name).write_text(json.dumps(value, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')


event_source_index = build_event_source_index(REPO)
exploration_source_index = build_exploration_source_index(REPO)
robot_source_index = build_robot_source_index(REPO)
attack_source_index = build_attack_source_index(REPO)

sources = {
    'SRC-RULEBOOK': {
        'sourceId': 'SRC-RULEBOOK', 'authority': 'official-primary', 'version': 'base rulebook, local official PDF',
        'path': 'docs/rulebooks/Nemesis_RT_Rulebook_official.pdf', 'sha256': sha('docs/rulebooks/Nemesis_RT_Rulebook_official.pdf'),
        'evidenceIndexPath': 'docs/rules/source-extraction/rulebook-visual-obligations.json',
    },
    'SRC-FAQ': {
        'sourceId': 'SRC-FAQ', 'authority': 'official-errata', 'version': 'v1.2 / 2026-06-08',
        'path': 'docs/rulebooks/Nemesis_RT_FAQ_v1.2.pdf', 'sha256': sha('docs/rulebooks/Nemesis_RT_FAQ_v1.2.pdf'),
        'evidenceIndexPath': 'docs/rules/source-extraction/faq-v1.2-source-extraction.json',
    },
    'SRC-ROOM-HELP': {
        'sourceId': 'SRC-ROOM-HELP', 'authority': 'official-component-reference', 'version': 'base Room Help Sheet',
        'path': 'docs/rulebooks/Nemesis_RT_Rooms_Sheet.pdf', 'sha256': sha('docs/rulebooks/Nemesis_RT_Rooms_Sheet.pdf'),
        'evidenceIndexPath': 'docs/rules/source-extraction/room-help-sheet.json',
    },
    'SRC-INTRUDER-HELP-QA': {
        'sourceId': 'SRC-INTRUDER-HELP-QA', 'authority': 'source-bound-component-scan', 'version': 'TTS Queen Alive face',
        'path': 'assets/tts-mod/extract/v2-dl/tree/cards/reference/card-053.png', 'sha256': sha('assets/tts-mod/extract/v2-dl/tree/cards/reference/card-053.png'),
        'evidenceIndexPath': 'docs/rules/source-extraction/intruder-help-sheet.json',
    },
    'SRC-INTRUDER-HELP-QD': {
        'sourceId': 'SRC-INTRUDER-HELP-QD', 'authority': 'source-bound-component-scan', 'version': 'TTS Queen Dead face',
        'path': 'assets/tts-mod/extract/v2-dl/tree/cards/reference/card-069.png', 'sha256': sha('assets/tts-mod/extract/v2-dl/tree/cards/reference/card-069.png'),
        'evidenceIndexPath': 'docs/rules/source-extraction/intruder-help-sheet.json',
    },
    'SRC-CARD-SEARCH-MEDICAL': {
        'sourceId': 'SRC-CARD-SEARCH-MEDICAL', 'authority': 'source-bound-component-scan', 'version': 'Medical Support Search face',
        'path': 'assets/tts-mod/extract/v2-dl/tree/cards/character/medical-support-047.jpg', 'sha256': sha('assets/tts-mod/extract/v2-dl/tree/cards/character/medical-support-047.jpg'),
        'evidenceIndexPath': 'assets/tts-mod/extract/card-text-corpus.json',
    },
    'SRC-CARD-REST': {
        'sourceId': 'SRC-CARD-REST', 'authority': 'source-bound-component-scan', 'version': 'project-owner-reviewed canonical Rest face',
        'path': 'assets/tts-mod/extract/v2-dl/tree/cards/game/action/rest.png', 'sha256': sha('assets/tts-mod/extract/v2-dl/tree/cards/game/action/rest.png'),
        'evidenceIndexPath': 'assets/tts-mod/extract/card-text-corpus.json',
    },
    'SRC-CARD-REST-MEDICAL': {
        'sourceId': 'SRC-CARD-REST-MEDICAL', 'authority': 'source-bound-component-scan', 'version': 'Medical Support Rest source variant',
        'path': 'assets/tts-mod/extract/v2-dl/tree/cards/character/medical-support-022.jpg', 'sha256': sha('assets/tts-mod/extract/v2-dl/tree/cards/character/medical-support-022.jpg'),
        'evidenceIndexPath': 'assets/tts-mod/extract/card-text-corpus.json',
    },
    'SRC-CARD-DUCK': {
        'sourceId': 'SRC-CARD-DUCK', 'authority': 'source-bound-component-scan', 'version': 'Contractor: Consultant Duck and Cover face',
        'path': 'assets/tts-mod/extract/v2-dl/tree/cards/character/contractor-026.jpg', 'sha256': sha('assets/tts-mod/extract/v2-dl/tree/cards/character/contractor-026.jpg'),
        'evidenceIndexPath': 'assets/tts-mod/extract/card-text-corpus.json',
    },
}
for source in event_source_registry_rows(event_source_index):
    sources[source['sourceId']] = source
for source in exploration_source_registry_rows(exploration_source_index):
    sources[source['sourceId']] = source
for source in robot_source_registry_rows(robot_source_index):
    sources[source['sourceId']] = source
for source in attack_source_registry_rows(attack_source_index):
    sources[source['sourceId']] = source
source_registry = {
    'schemaVersion': 1, 'recordType': 'semantic-source-registry',
    'authorityOrder': ['official-errata', 'official-primary', 'official-component-reference', 'source-bound-component-scan', 'licensed-digital-secondary', 'project-interpretation'],
    'counts': {'sources': len(sources)}, 'sources': [sources[source_id] for source_id in sorted(sources)],
}

# JSON Schema is intentionally explicit enough for external consumers while the
# project validator adds cross-file/reference/authority checks without a third-party package.
semantic_schema = {
    '$schema': 'https://json-schema.org/draft/2020-12/schema',
    '$id': 'https://example.invalid/nemesis-retaliation/semantic-rule.schema.json',
    'title': 'Nemesis Retaliation semantic rule record',
    'type': 'object',
    'required': ['schemaVersion','recordType','recordRevision','ruleId','title','status','ruleKind','applicability','authority','sourceAssertions','termRefs','taxonRefs','namedIdentityRefs','timing','participants','modality','preconditions','decisions','informationPolicy','costs','targets','operations','partialResolution','duration','stacking','outcomes','unresolvedQuestionRefs','sourceVariants','implementationBoundary'],
    'additionalProperties': False,
    'properties': {
        'schemaVersion': {'const':1},
        'recordType': {'const':'semantic-rule'},
        'recordRevision': {'type':'integer','minimum':1},
        'ruleId': {'type':'string','pattern':'^SEM-[A-Z0-9-]+$'},
        'title': {'type':'string','minLength':1},
        'status': {'enum':['source-backed','source-backed-with-open-question','source-variant']},
        'ruleKind': {'enum':['sequence','procedure','action','reaction','component-effect','event','dispatcher','endgame','constraint']},
        'applicability': {'type':'object','required':['game','mode','playerCount'], 'properties':{'game':{'const':'Nemesis: Retaliation'},'mode':{'enum':['base','base-standard']},'playerCount':{'type':['object','null']}}},
        'authority': {'type':'object','required':['highest','interpretation'], 'properties':{'highest':{'enum':['official-errata','official-primary','official-component-reference','source-bound-component-scan']},'interpretation':{'enum':['verbatim-structure','source-composed','open-alternatives']}}},
        'sourceAssertions': {'type':'array','minItems':1},
        'termRefs': {'type':'array'}, 'taxonRefs': {'type':'array'}, 'namedIdentityRefs': {'type':'array'},
        'timing': {'type':'object'}, 'participants': {'type':'array'}, 'modality': {'enum':['must','may','cannot','if-able','mixed']},
        'preconditions': {'type':'array'}, 'decisions': {'type':'array'}, 'informationPolicy': {'type':'array'}, 'costs': {'type':'array'}, 'targets': {'type':'array'}, 'operations': {'type':'array','minItems':1},
        'partialResolution': {'type':'object'}, 'duration': {'type':'object'}, 'stacking': {'type':'object'}, 'outcomes': {'type':'array'}, 'unresolvedQuestionRefs': {'type':'array'}, 'sourceVariants': {'type':'array'},
        'implementationBoundary': {'const':'implementation-neutral; no engine, UI, network, storage, or serialization mapping'},
    },
}

semantic_nodes = {
    'schemaVersion': 1,
    'recordType': 'semantic-node-registry',
    'counts': {'nodes': 26, 'stateValues': 19, 'zones': 2, 'positions': 2, 'visibilityScopes': 3},
    'nodes': [
        {'semanticNodeId':'sem.state.phase.passed','kind':'state-value','label':'Passed for current Player Phase','sourceEvidence':['docs/rules/01-round-and-turns.md:RT-007']},
        {'semanticNodeId':'sem.state.participation.active','kind':'state-value','label':'Actively participating','sourceEvidence':['docs/rules/01-round-and-turns.md:RT-014']},
        {'semanticNodeId':'sem.state.participation.in-lander','kind':'state-value','label':'Inside Lander, not yet Escaped','sourceEvidence':['docs/rules/01-round-and-turns.md:RT-014']},
        {'semanticNodeId':'sem.state.participation.escaped','kind':'state-value','label':'Escaped','sourceEvidence':['docs/rules/03-intruders-and-survival.md:INT-009']},
        {'semanticNodeId':'sem.state.participation.hibernated','kind':'state-value','label':'Hibernated','sourceEvidence':['docs/rules/03-intruders-and-survival.md:INT-009']},
        {'semanticNodeId':'sem.state.participation.dead','kind':'state-value','label':'Dead/no longer participating','sourceEvidence':['docs/rules/01-round-and-turns.md:RT-014']},
        {'semanticNodeId':'sem.state.game.running','kind':'state-value','label':'Game running','sourceEvidence':['docs/rules/01-round-and-turns.md:RT-015']},
        {'semanticNodeId':'sem.state.game.ending','kind':'state-value','label':'Endgame sequence resolving','sourceEvidence':['docs/rules/03-intruders-and-survival.md:INT-011']},
        {'semanticNodeId':'sem.state.game.ended','kind':'state-value','label':'Game ended','sourceEvidence':['docs/rules/03-intruders-and-survival.md:INT-011']},
        {'semanticNodeId':'sem.state.outcome.winner','kind':'state-value','label':'Winner','sourceEvidence':['docs/rules/03-intruders-and-survival.md:INT-011']},
        {'semanticNodeId':'sem.state.outcome.loser','kind':'state-value','label':'Loser','sourceEvidence':['docs/rules/03-intruders-and-survival.md:INT-011']},
        {'semanticNodeId':'sem.state.room.always-secured','kind':'state-value','label':'Permanent always-secured Room status','sourceEvidence':['docs/rulebooks/Nemesis_RT_FAQ_v1.2.pdf:Rooms #2']},
        {'semanticNodeId':'sem.state.room.secure-prohibited','kind':'state-value','label':'Room cannot receive Secure tokens','sourceEvidence':['docs/rulebooks/Nemesis_RT_Rooms_Sheet.pdf:Rooms 04, 12, 25']},
        {'semanticNodeId':'sem.state.room.malfunction-prohibited','kind':'state-value','label':'Room cannot receive Malfunction markers','sourceEvidence':['docs/rulebooks/Nemesis_RT_Rooms_Sheet.pdf:Room 25']},
        {'semanticNodeId':'sem.state.room.nest-destroyed','kind':'state-value','label':'Nest destroyed','sourceEvidence':['docs/rulebooks/Nemesis_RT_Rulebook_official.pdf:printed page 7','docs/rulebooks/Nemesis_RT_FAQ_v1.2.pdf:Rooms #4']},
        {'semanticNodeId':'sem.state.robot-card.unrevealed','kind':'state-value','label':'Selected Robot card face down and unrevealed','sourceEvidence':['docs/rulebooks/Nemesis_RT_Rulebook_official.pdf:printed pages 8 and 37']},
        {'semanticNodeId':'sem.state.robot-card.revealed','kind':'state-value','label':'Selected Robot card face up and public','sourceEvidence':['docs/rulebooks/Nemesis_RT_Rulebook_official.pdf:printed page 37']},
        {'semanticNodeId':'sem.state.robot.operational','kind':'state-value','label':'Robot operational and available for otherwise legal activation','sourceEvidence':['docs/rulebooks/Nemesis_RT_Rulebook_official.pdf:printed page 37']},
        {'semanticNodeId':'sem.state.robot.broken','kind':'state-value','label':'Robot broken by a Malfunction marker','sourceEvidence':['docs/rulebooks/Nemesis_RT_Rulebook_official.pdf:printed pages 22 and 37']},
        {'semanticNodeId':'sem.zone.temporary-private-inspection','kind':'zone','label':'Temporary private inspection set','sourceEvidence':['docs/rules/02-character-actions.md:ACT-SEARCH-001']},
        {'semanticNodeId':'sem.zone.card-in-resolution','kind':'zone','label':'Card currently resolving','sourceEvidence':['docs/rules/02-character-actions.md:ACT-CARD-001']},
        {'semanticNodeId':'sem.position.deck-top','kind':'position','label':'Top of deck/pile','sourceEvidence':['docs/rules/03-intruders-and-survival.md:INT-008']},
        {'semanticNodeId':'sem.position.deck-bottom','kind':'position','label':'Bottom of deck/pile','sourceEvidence':['docs/rules/02-character-actions.md:ACT-SEARCH-001']},
        {'semanticNodeId':'sem.visibility.public','kind':'visibility-scope','label':'Public','sourceEvidence':['docs/rules/01-round-and-turns.md']},
        {'semanticNodeId':'sem.visibility.owner-private','kind':'visibility-scope','label':'Owner-private','sourceEvidence':['docs/rules/02-character-actions.md:ACT-SEARCH-001']},
        {'semanticNodeId':'sem.visibility.scanning-player','kind':'visibility-scope','label':'Scanning player','sourceEvidence':['docs/rules/03-intruders-and-survival.md:INT-008']},
    ],
}

room_icon_denotations = build_room_icon_denotations(
    json.loads((REPO/'docs/rules/source-extraction/room-help-sheet.json').read_text()),
    json.loads((REPO/'docs/rules/vocabulary/canonical-vocabulary.json').read_text()),
)


def assertion(assertion_id, source_id, locator, supports, excerpt=None, evidence_record=None):
    source = sources[source_id]
    return {'assertionId': assertion_id, 'sourceId': source_id, 'sourcePath': source['path'], 'sourceSha256': source['sha256'], 'sourceAuthority': source['authority'], 'sourceVersion': source['version'], 'locator': locator, 'supportsFields': supports, 'sourceText': excerpt, 'textKind': 'normalized-paraphrase', 'evidenceRecord': evidence_record}


def timing(window_id, anchor, relation, recurrence='once-per-invocation'):
    return {'windowId': window_id, 'anchorTaxonId': anchor, 'relation': relation, 'recurrence': recurrence}


def participant(pid, kind, taxon=None, role=None):
    return {'participantId': pid, 'participantKind': kind, 'taxonId': taxon, 'role': role}


def condition(cid, operator, args, sources, scope='record-precondition'):
    return {'conditionId': cid, 'scope': scope, 'expression': {'operator': operator, 'args': args}, 'sourceAssertionIds': sources}


def decision(did, owner, mode, minimum, maximum, decline, visibility, options):
    return {'decisionId': did, 'ownerRef': owner, 'selectionMode': mode, 'cardinality': {'min': minimum, 'max': maximum}, 'declineAllowed': decline, 'visibility': visibility, 'options': options}


def operation(step, order, op_type, modality, subject, obj, sources, *, conditions=None, decision_ref=None, target_ref=None, transition=None, value_change=None, invoke=None, repeat=None, notes=None):
    return {'stepId': step, 'sequence': order, 'operationType': op_type, 'modality': modality, 'subjectRef': subject, 'objectRef': obj, 'conditionRefs': conditions or [], 'decisionRef': decision_ref, 'targetRef': target_ref, 'transition': transition, 'valueChange': value_change, 'invokeRuleId': invoke, 'repeat': repeat, 'sourceAssertionIds': sources, 'notes': notes}


def record(rule_id, title, status, rule_kind, authority_highest, authority_interpretation, source_assertions, term_refs, taxon_refs, named_refs, timing_value, participants, modality, preconditions, decisions, information, costs, targets, operations, partial, duration, stacking, outcomes, unresolved, variants):
    known_conditions = {item['conditionId'] for item in preconditions}
    generated_conditions = []
    for op in operations:
        normalized_refs = []
        for index, reference in enumerate(op['conditionRefs'], 1):
            if reference in known_conditions:
                normalized_refs.append(reference)
                continue
            condition_id = f"{op['stepId']}-C{index:02d}"
            generated_conditions.append(condition(condition_id, 'predicate', [{'predicate': reference}], op['sourceAssertionIds'], scope='operation-guard'))
            known_conditions.add(condition_id)
            normalized_refs.append(condition_id)
        op['conditionRefs'] = normalized_refs
    preconditions = [*preconditions, *generated_conditions]
    return {'schemaVersion':1,'recordType':'semantic-rule','recordRevision':1,'ruleId':rule_id,'title':title,'status':status,'ruleKind':rule_kind,'applicability':{'game':'Nemesis: Retaliation','mode':'base-standard','playerCount':None},'authority':{'highest':authority_highest,'interpretation':authority_interpretation},'sourceAssertions':source_assertions,'termRefs':sorted(set(term_refs)),'taxonRefs':sorted(set(taxon_refs)),'namedIdentityRefs':sorted(set(named_refs)),'timing':timing_value,'participants':participants,'modality':modality,'preconditions':preconditions,'decisions':decisions,'informationPolicy':information,'costs':costs,'targets':targets,'operations':operations,'partialResolution':partial,'duration':duration,'stacking':stacking,'outcomes':outcomes,'unresolvedQuestionRefs':unresolved,'sourceVariants':variants,'implementationBoundary':'implementation-neutral; no engine, UI, network, storage, or serialization mapping'}

records = []

records.append(record(
    'SEM-RT-001','Round phase sequence','source-backed','sequence','official-primary','verbatim-structure',
    [assertion('SA-RT001-1','SRC-RULEBOOK','printed pages 12–15 / rulebook_text lines 2939–2986',['timing','operations'],'The game is played in a series of Rounds. Each Round contains Player, Intruder, Event, and Cleanup Phases in that order.','docs/rules/01-round-and-turns.md:RT-001')],
    ['term.round','term.player-phase','term.intruder-phase','term.event-phase','term.cleanup-phase'],
    ['tax.process.temporal.round','tax.process.temporal.phase.player','tax.process.temporal.phase.intruder','tax.process.temporal.phase.event','tax.process.temporal.phase.cleanup'],[],
    timing('TW-ROUND','tax.process.temporal.round','during','once-per-round'),[participant('P-RULES','rules-system')],'must',[],[],[{'informationId':'I-ROUND-STATE','subjectRef':'current phase/round','audience':'public','revealTrigger':'continuous','secrecy':'none'}],[],[],
    [operation('S01',1,'invoke-process','must','rules-system','Player Phase',['SA-RT001-1']),operation('S02',2,'invoke-process','must','rules-system','Intruder Phase',['SA-RT001-1']),operation('S03',3,'invoke-process','must','rules-system','Event Phase',['SA-RT001-1']),operation('S04',4,'invoke-process','must','rules-system','Cleanup Phase',['SA-RT001-1'])],
    {'policy':'ordered-complete','unit':'phase','onImpossible':'not-specified'}, {'kind':'round'}, {'policy':'not-applicable'}, [], [], []))

records.append(record(
    'SEM-RT-004','Player Phase rotation','source-backed','sequence','official-primary','verbatim-structure',
    [assertion('SA-RT004-1','SRC-RULEBOOK','printed page 13 / lines 2987–3004',['timing','operations','targets'],'During this Phase players take their Turns in clockwise order, beginning with the Starting Player. If a given player has Passed, they are skipped.','docs/rules/01-round-and-turns.md:RT-004')],
    ['term.player-phase','term.turn','term.turn-order','term.starting-player','term.pass'],['tax.process.temporal.phase.player','tax.process.temporal.turn','tax.value.turn-order','tax.role.starting-player'],[],
    timing('TW-PLAYER-PHASE','tax.process.temporal.phase.player','during','once-per-round'),[participant('P-RULES','rules-system'),participant('P-PLAYERS','collection','tax.entity.agent.player')],'must',
    [condition('C-ALL-PASSED','predicate',[{'predicate':'all eligible players have Passed'}],['SA-RT004-1'])],[],[{'informationId':'I-TURN-ORDER','subjectRef':'turn order and passed status','audience':'public','revealTrigger':'continuous','secrecy':'none'}],[],
    [{'targetId':'T-NEXT-PLAYER','selectorRef':'rules-system','eligibleTaxonIds':['tax.entity.agent.player'],'cardinality':{'min':1,'max':1},'selectionMode':'deterministic-turn-order','visibility':'public'}],
    [operation('S01',1,'set-state','must','rules-system','Turn-order cursor at Starting Player',['SA-RT004-1']),operation('S02',2,'invoke-process','must','next non-Passed Player','Turn',['SA-RT004-1'],target_ref='T-NEXT-PLAYER',repeat={'afterEach':'advance clockwise to next non-Passed Player','untilConditionRef':'C-ALL-PASSED'}),operation('S03',3,'invoke-process','must','rules-system','Intruder Phase',['SA-RT004-1'],conditions=['C-ALL-PASSED'])],
    {'policy':'ordered-complete','unit':'turn rotation','onImpossible':'skip players who have Passed'}, {'kind':'phase'}, {'policy':'not-applicable'}, [], [], []))

records.append(record(
    'SEM-RT-005','Player Turn','source-backed-with-open-question','sequence','official-primary','open-alternatives',
    [assertion('SA-RT005-1','SRC-RULEBOOK','printed pages 12–13 / lines 2854–2864, 2929–2934',['operations','decisions'],'Perform exactly two Actions, then resolve Oxygen loss, then Fire damage.','docs/rules/01-round-and-turns.md:RT-005'),assertion('SA-RT005-2','SRC-RULEBOOK','printed page 18 / death',['unresolvedQuestionRefs'],'A dead Character no longer takes part in the game.','docs/rules/open-questions.md:OQ-004')],
    ['term.turn','term.action','term.pass','icon.oxygen','icon.fire','icon.characterHealth'],['tax.process.temporal.turn','tax.process.action','tax.value.resource.oxygen','tax.entity.component.marker.fire'],[],
    timing('TW-TURN','tax.process.temporal.turn','during','once-per-player-turn'),[participant('P-ACTIVE-PLAYER','actor','tax.entity.agent.player'),participant('P-ACTIVE-CHARACTER','controlled-actor','tax.entity.agent.character')],'must',[],
    [decision('D-ACTION-1','P-ACTIVE-PLAYER','player-choice',1,1,False,'public-on-declaration',['any fully resolvable legal Action']),decision('D-ACTION-2','P-ACTIVE-PLAYER','player-choice',1,1,False,'public-on-declaration',['any fully resolvable legal Action, including Pass'])],
    [{'informationId':'I-HAND','subjectRef':'unselected hand cards','audience':'owner-private','revealTrigger':'source-specific play/discard','secrecy':'identities hidden from other players'}],[],[],
    [operation('S01',1,'invoke-selected-process','must','P-ACTIVE-CHARACTER','selected Action',['SA-RT005-1'],decision_ref='D-ACTION-1'),operation('S02',2,'invoke-selected-process','if-able','P-ACTIVE-CHARACTER','selected Action',['SA-RT005-1'],conditions=['current Player has not Passed and Character remains participating'],decision_ref='D-ACTION-2'),operation('S03',3,'change-value','if-able','P-ACTIVE-CHARACTER','Oxygen',['SA-RT005-1'],conditions=['Character is in a Section with inactive Life Support'],value_change={'amount':-1,'valueTaxonId':'tax.value.resource.oxygen'}),operation('S04',4,'change-value','if-able','P-ACTIVE-CHARACTER','Character Health',['SA-RT005-1'],conditions=['Character is in a Room with Fire'],value_change={'amount':-1,'valueTaxonId':'tax.state.health.point'})],
    {'policy':'ordered-complete','unit':'turn step','onImpossible':'Pass remains an Action option; mid-Turn death continuation is unresolved'}, {'kind':'turn'}, {'policy':'not-applicable'}, [], ['OQ-004'], []))

records.append(record(
    'SEM-RT-007','Pass Action','source-backed','action','official-primary','verbatim-structure',
    [assertion('SA-RT007-1','SRC-RULEBOOK','printed pages 13–14 / Passing',['decisions','operations','duration'],'A player may discard any number of Action and Contamination cards from hand; the Turn ends and the player is skipped for the rest of the Player Phase.','docs/rules/01-round-and-turns.md:RT-007')],
    ['term.pass','icon.actionCard','term.contamination-card'],['tax.process.action.pass','tax.entity.component.card.action','tax.entity.component.card.contamination'],[],
    timing('TW-PASS','tax.process.temporal.turn','during','once-when-chosen'),[participant('P-ACTIVE-PLAYER','actor','tax.entity.agent.player')],'may',[],
    [decision('D-DISCARD-SUBSET','P-ACTIVE-PLAYER','player-choice',0,None,True,'owner-private-until-discard',['any subset of Action and Contamination cards in own hand'])],
    [{'informationId':'I-PASS-HAND','subjectRef':'unselected hand cards','audience':'owner-private','revealTrigger':'never by Pass','secrecy':'identities hidden'},{'informationId':'I-PASS-DISCARDS','subjectRef':'selected discarded cards','audience':'public','revealTrigger':'discard','secrecy':'component/card identity is public; hidden INFECTED text remains governed by scanning'}],[],[],
    [operation('S01',1,'transition-zone','may','P-ACTIVE-PLAYER','selected cards',['SA-RT007-1'],decision_ref='D-DISCARD-SUBSET',transition={'from':'tax.scaffold.zone.hand','to':'tax.scaffold.zone.discard-pile'}),operation('S02',2,'set-state','must','P-ACTIVE-PLAYER','sem.state.phase.passed',['SA-RT007-1']),operation('S03',3,'end-action-window','must','P-ACTIVE-PLAYER','remaining Action opportunities in current Turn',['SA-RT007-1'],notes='Return to the parent Turn so mandatory oxygen loss and fire damage still resolve.')],
    {'policy':'all-or-nothing-selection','unit':'Pass Action','onImpossible':'not applicable; zero-card subset is legal'}, {'kind':'until-end-of-current-player-phase'}, {'policy':'one Passed state per Player Phase'}, [], [], []))

records.append(record(
    'SEM-ACT-MOVE-001','Move Action and Movement Sequence','source-backed-with-open-question','action','official-errata','open-alternatives',
    [assertion('SA-MOVE-1','SRC-RULEBOOK','printed pages 12 and 24–25',['costs','preconditions','targets','operations'],'Move costs 1 Action card; choose an adjacent Corridor, resolve opportunity attacks, resolve destination, then make a Noise roll.','docs/rules/02-character-actions.md:ACT-MOVE-001'),assertion('SA-MOVE-2','SRC-FAQ','Action cards #3',['outcomes'],'Attack prevention during Movement applies to opportunity attacks, not a Hazard-result attack.','docs/rules/02-character-actions.md:ACT-MOVE-001')],
    ['term.move','term.movement-sequence','term.opportunity-attack','term.noise-roll','term.corridor','term.room','term.closed'],['tax.process.action.move','tax.process.sequence.movement','tax.process.attack.opportunity','tax.entity.spatial.corridor','tax.entity.spatial.room','tax.state.closed'],[],
    timing('TW-MOVE','tax.process.temporal.turn','during','per-selected-Move'),[participant('P-ACTIVE-PLAYER','decision-owner','tax.entity.agent.player'),participant('P-MOVING-CHARACTER','actor','tax.entity.agent.character')],'must',
    [condition('C-LEGAL-CORRIDOR','all',[{'predicate':'Corridor is adjacent to origin Room'},{'predicate':'path is not blocked by a Closed Door'},{'predicate':'destination branch is fully resolvable'}],['SA-MOVE-1'])],
    [decision('D-PAYMENT','P-ACTIVE-PLAYER','player-choice',1,1,False,'owner-private-until-discard',['own Action cards in hand']),decision('D-CORRIDOR','P-ACTIVE-PLAYER','player-choice',1,1,False,'public-on-declaration',['adjacent Corridors satisfying C-LEGAL-CORRIDOR'])],
    [{'informationId':'I-MOVE-PAYMENT','subjectRef':'paid Action card identity','audience':'public','revealTrigger':'payment discard','secrecy':'none'}],
    [{'costId':'COST-MOVE','payerRef':'P-ACTIVE-PLAYER','resourceTermId':'icon.actionCard','quantity':1,'selectionDecisionRef':'D-PAYMENT','transition':{'from':'tax.scaffold.zone.hand','to':'tax.scaffold.zone.discard-pile'}}],
    [{'targetId':'T-CORRIDOR','selectorRef':'P-ACTIVE-PLAYER','eligibleTaxonIds':['tax.entity.spatial.corridor'],'cardinality':{'min':1,'max':1},'selectionMode':'player-choice','visibility':'public'}],
    [operation('S01',1,'pay-cost','must','P-ACTIVE-PLAYER','COST-MOVE',['SA-MOVE-1'],decision_ref='D-PAYMENT'),operation('S02',2,'select-target','must','P-ACTIVE-PLAYER','adjacent Corridor',['SA-MOVE-1'],decision_ref='D-CORRIDOR',target_ref='T-CORRIDOR'),operation('S03',3,'resolve-attacks','if-able','Intruders in origin Room and selected Corridor','P-MOVING-CHARACTER',['SA-MOVE-1'],repeat={'order':'largest-first','max':3},notes='If more than three equal-largest Intruders qualify, source tie-breaking is SEM-Q-003.'),operation('S04',4,'branch','must','rules-system','destination branch',['SA-MOVE-1'],conditions=['destination is Discovered Room OR destination is Undiscovered Room slot']),operation('S05',5,'move-entity','must','P-MOVING-CHARACTER','destination Room',['SA-MOVE-1'],conditions=['destination is Discovered Room']),operation('S06',6,'invoke-process','must','P-MOVING-CHARACTER','Exploration Sequence',['SA-MOVE-1'],conditions=['selected Corridor is Unexplored'],invoke='SEM-ACT-EXPLORE-001'),operation('S07',7,'invoke-process','must','P-MOVING-CHARACTER','Noise Roll',['SA-MOVE-1'],conditions=['destination is an already Discovered Room'],notes='Unexplored Movement delegates post-Movement Noise accounting to SEM-ACT-EXPLORE-001 because SEM-Q-002 remains open.')],
    {'policy':'all-or-nothing-selection','unit':'Move Action','onImpossible':'Action may be selected only if fully resolvable'}, {'kind':'instantaneous-action'}, {'policy':'repeatable Action'}, [], ['SEM-Q-003'], []))

records.append(record(
    'SEM-ACT-EXPLORE-001','Exploration Sequence','source-backed-with-open-question','sequence','official-errata','open-alternatives',
    [assertion('SA-EXP-1','SRC-RULEBOOK','printed page 24 / Exploration Sequence',['timing','operations','partialResolution'],'Draw an Exploration card, set up Room/Corridors/markers, move Character, resolve Entrance Effect, discard card. Invalid additional Corridors are omitted.','docs/rules/02-character-actions.md:ACT-EXPLORE-001'),assertion('SA-EXP-2','SRC-FAQ','General rules #4–5',['operations','partialResolution'],'Close Doors applies only around the new Room; remove-from-game text is outside Entrance Effect.','docs/rules/02-character-actions.md:ACT-EXPLORE-001'),assertion('SA-EXP-3','SRC-RULEBOOK','printed pages 25–27 / Noise after every Movement and worked example',['operations','unresolvedQuestionRefs'],'Every Movement requires a Noise roll, while the worked exploratory example resolves one Entrance-Effect Noise roll and then finishes the card.','docs/rules/open-questions.md')],
    ['term.exploration-sequence','term.exploration-card','term.unexplored-corridor','term.undiscovered','term.discovered'],['tax.process.sequence.exploration','tax.entity.component.card.exploration','tax.state.corridor.unexplored','tax.state.discovery.undiscovered','tax.state.discovery.discovered'],[],
    timing('TW-EXPLORE','tax.process.sequence.movement','when-triggered','per-Unexplored-destination'),[participant('P-EXPLORER','actor','tax.entity.agent.character'),participant('P-RULES','rules-system')],'must',
    [condition('C-EXPLORE','all',[{'predicate':'Movement reaches an Unexplored Corridor'},{'predicate':'destination Room slot is empty and Undiscovered'}],['SA-EXP-1'])],[],[{'informationId':'I-EXPLORATION-CARD','subjectRef':'drawn Exploration card','audience':'public','revealTrigger':'draw','secrecy':'none'}],[],[],
    [operation('S01',1,'shuffle','if-able','P-RULES','non-removed Exploration discard cards into Exploration deck',['SA-EXP-1'],conditions=['Exploration deck is empty']),operation('S02',2,'draw-random','must','P-RULES','top Exploration card into resolution',['SA-EXP-1']),operation('S03',3,'invoke-selected-process','must','P-RULES','exact Exploration-card semantic record selected by locked untitled source occurrence identity',['SA-EXP-1','SA-EXP-2'],notes='Dispatch uses the exact TTS CardID/GUID/source tuple and diagram crosswalk, never title, folder, display name, BGA number alone, or CardID modulo.'),operation('S04',4,'resolve-open-alternative','must','P-RULES','SEM-Q-002 post-Movement Noise accounting',['SA-EXP-3'],notes='No default: either the Entrance Noise satisfies the universal roll or a separate universal roll also occurs.')],
    {'policy':'source-conditional-steps','unit':'draw/dispatch and exact occurrence-level source unit','onImpossible':'The invoked occurrence owns invalid-Corridor, finite-component, Entrance-effect, and lifecycle boundaries; SEM-Q-002 remains unresolved'}, {'kind':'instantaneous-sequence'}, {'policy':'not-applicable'}, [], ['SEM-Q-002'], []))
records[-1]['operations'][2]['dispatchRuleIds']=list(EXPLORATION_RULE_IDS)

records.append(record(
    'SEM-ACT-SEARCH-001','Search Action-card effect','source-backed','component-effect','official-primary','source-composed',
    [assertion('SA-SEARCH-1','SRC-RULEBOOK','printed page 28 / lines 4849–4865',['preconditions','decisions','informationPolicy','operations'],'Draw 1 Item for each Item Icon, keep 1, put the rest on the bottoms of their respective decks, and do not reveal unchosen Items.','docs/rules/02-character-actions.md:ACT-SEARCH-001'),assertion('SA-SEARCH-2','SRC-CARD-SEARCH-MEDICAL','exact card face',['timing','operations','sourceVariants'],'For each Item Icon in your Room draw 1 Item of the corresponding type. You may keep 1 of them and discard the rest.','assets/tts-mod/extract/card-text-corpus.json'),assertion('SA-SEARCH-3','SRC-RULEBOOK','printed page 13 / Playing Action Cards',['operations'],'After resolving an Action card, discard that card.','docs/rules/02-character-actions.md:ACT-CARD-001')],
    ['term.search','term.item','term.room','term.backpack','term.hand-slot','term.armor-item','icon.notInCombat'],['tax.process.card-effect.search','tax.entity.component.card.item','tax.entity.spatial.room','tax.scaffold.zone.backpack','tax.entity.component.slot.hand','tax.entity.component.card.item.armor','tax.state.combat.not-in-combat'],['NI-0426'],
    timing('TW-SEARCH','tax.process.action.basic','when-action-card-played','per-played-Search-card'),[participant('P-SEARCHER','actor','tax.entity.agent.character'),participant('P-OWNER','decision-owner','tax.entity.agent.player')],'must',
    [condition('C-SEARCH-LEGAL','all',[{'predicate':'Searcher is Not In Combat'},{'predicate':'Room has at least 1 Item Icon'},{'predicate':'the draw/keep/return sequence is fully resolvable'}],['SA-SEARCH-1','SA-SEARCH-2'])],
    [decision('D-KEEP-ITEM','P-OWNER','player-choice',1,1,False,'owner-private',['drawn Item cards'])],
    [{'informationId':'I-SEARCH-CANDIDATES','subjectRef':'drawn Item identities','audience':'owner-private','revealTrigger':'chosen Item enters a public area or is used','secrecy':'unchosen Items must not be revealed'},{'informationId':'I-BACKPACK-ITEM','subjectRef':'chosen Regular Item in Backpack','audience':'owner-private','revealTrigger':'use or source-defined reveal','secrecy':'Backpack contents hidden'}],[],
    [{'targetId':'T-KEPT-ITEM','selectorRef':'P-OWNER','eligibleTaxonIds':['tax.entity.component.card.item'],'cardinality':{'min':1,'max':1},'selectionMode':'player-choice','visibility':'owner-private'}],
    [operation('S01',1,'draw-random','must','P-SEARCHER','1 Item from corresponding deck per Room Item Icon',['SA-SEARCH-1']),operation('S02',2,'select-target','must','P-OWNER','one drawn Item',['SA-SEARCH-1'],decision_ref='D-KEEP-ITEM',target_ref='T-KEPT-ITEM'),operation('S03',3,'transition-zone','must','P-OWNER','chosen Item',['SA-SEARCH-1'],transition={'from':'sem.zone.temporary-private-inspection','to':'Backpack, Hand slot, or Armor position according to Item class'}),operation('S04',4,'transition-zone','must','P-OWNER','each unchosen Item',['SA-SEARCH-1'],transition={'from':'sem.zone.temporary-private-inspection','to':'tax.scaffold.zone.deck','positionRef':'sem.position.deck-bottom'}),operation('S05',5,'transition-zone','must','P-OWNER','played Search Action card',['SA-SEARCH-2','SA-SEARCH-3'],transition={'from':'tax.scaffold.zone.hand','to':'tax.scaffold.zone.discard-pile','positionRef':'sem.position.deck-top'})],
    {'policy':'all-or-nothing-selection','unit':'Search effect','onImpossible':'Action/card effect may be selected only if fully resolvable'}, {'kind':'instantaneous-card-effect'}, {'policy':'one chosen Item; unchosen returns are independent per deck'}, [], [],
    [{'variantId':'SV-SEARCH-CARD-SHORTHAND','sourceId':'SRC-CARD-SEARCH-MEDICAL','sourceAssertionId':'SA-SEARCH-2','difference':'Card says “may keep 1” and “discard the rest”; higher-authority rulebook says pick 1, places the rest on respective deck bottoms, and prohibits revealing unchosen Items.','resolution':'official-primary rulebook controls the general Search procedure while exact optionality/destination card wording remains preserved'}]))

records.append(record(
    'SEM-ACT-REST-001','Rest card modifier over Infection Procedure','source-backed','component-effect','official-primary','source-composed',
    [assertion('SA-REST-1','SRC-CARD-REST','exact card face',['preconditions','operations','sourceVariants'],'Resolve the Infection Procedure. Remove all Uninfected cards from the game.','assets/tts-mod/extract/card-text-corpus.json'),assertion('SA-REST-2','SRC-RULEBOOK','printed page 38 / lines 6079–6098',['operations'],'Scan all Contamination cards in hand; place a Larva if any is Infected and none is present; place Contaminations on top of discard pile.','docs/rules/03-intruders-and-survival.md:INT-008'),assertion('SA-REST-3','SRC-RULEBOOK','printed page 13 / Playing Action Cards',['operations'],'After resolving an Action card, discard that card.','docs/rules/02-character-actions.md:ACT-CARD-001'),assertion('SA-REST-V1','SRC-CARD-REST-MEDICAL','exact Medical Support variant face',['sourceVariants'],'Remove all non-Infected cards from the game instead of discarding them.','assets/tts-mod/extract/card-text-corpus.json')],
    ['term.infection-procedure','term.contamination-card','term.infected','icon.notInCombat'],['tax.process.procedure.infection','tax.entity.component.card.contamination','tax.state.infection.infected','tax.state.combat.not-in-combat'],['NI-0410'],
    timing('TW-REST','tax.process.action.basic','when-action-card-played','per-played-Rest-card'),[participant('P-RESTING','actor','tax.entity.agent.character'),participant('P-OWNER','controller','tax.entity.agent.player')],'must',
    [condition('C-REST-LEGAL','all',[{'predicate':'Character is Not In Combat'},{'predicate':'Rest/Infection sequence is fully resolvable'}],['SA-REST-1','SA-REST-2'])],[],
    [{'informationId':'I-SCAN','subjectRef':'hidden Contamination text/result','audience':'scanning-player','revealTrigger':'scan instruction','secrecy':'hidden before scan; post-scan disclosure is not specified by the checked source'}],[],[],
    [operation('S01',1,'inspect-private','must','P-OWNER','all Contamination cards in hand',['SA-REST-2']),operation('S02',2,'evaluate-condition','must','P-OWNER','exact word INFECTED on each scanned card',['SA-REST-2']),operation('S03',3,'place-component','if-able','P-RESTING','1 Larva on Character board',['SA-REST-2'],conditions=['at least one scanned card is Infected','Character board has no Larva']),operation('S04',4,'transition-zone','must','P-OWNER','all scanned Uninfected Contamination cards',['SA-REST-1'],transition={'from':'tax.scaffold.zone.hand','to':'tax.scaffold.zone.removed-from-game'}),operation('S05',5,'transition-zone','must','P-OWNER','remaining Infected Contamination cards',['SA-REST-2'],transition={'from':'tax.scaffold.zone.hand','to':'top of tax.scaffold.zone.discard-pile'}),operation('S06',6,'transition-zone','must','P-OWNER','played Rest Action card',['SA-REST-1','SA-REST-3'],transition={'from':'tax.scaffold.zone.hand','to':'tax.scaffold.zone.discard-pile'})],
    {'policy':'all-or-nothing-selection','unit':'Rest card effect','onImpossible':'card may be selected only if fully resolvable'}, {'kind':'instantaneous-card-effect'}, {'policy':'non-Infected removal replaces normal Infection Procedure discard destination for those cards'}, [], [],
    [{'variantId':'SV-REST-MEDICAL','sourceId':'SRC-CARD-REST-MEDICAL','sourceAssertionId':'SA-REST-V1','difference':'Medical Support source face says non-Infected and “instead of discarding them”; exact punctuation and footer remain separate.','resolution':'pilot encodes only the reviewed canonical source tuple plus the official Procedure; the Medical Support variant is not substituted'}]))

records.append(record(
    'SEM-REACTION-DUCK-001','Duck and Cover Reaction redirect','source-backed-with-open-question','reaction','official-primary','open-alternatives',
    [assertion('SA-DUCK-1','SRC-CARD-DUCK','Reaction panel',['timing','preconditions','targets','operations'],'When you would be Attacked by an Intruder in a Room with another Character: The Intruder Attacks the other Character instead.','assets/tts-mod/extract/card-text-corpus.json'),assertion('SA-DUCK-2','SRC-RULEBOOK','printed pages 13–14 / Reactions',['timing','duration','operations'],'A player may use a Reaction when its condition is met; resolve it, then discard the card; it is not an Action.','docs/rules/01-round-and-turns.md:RT-003')],
    ['term.reaction','term.attack','icon.intruder','icon.character'],['tax.process.card-effect.reaction','tax.process.attack','tax.entity.agent.intruder','tax.entity.agent.character'],[],
    timing('TW-DUCK','tax.process.attack','before-attack-resolution','when-trigger-condition-met'),[participant('P-ORIGINAL-TARGET','actor','tax.entity.agent.character'),participant('P-OWNER','decision-owner','tax.entity.agent.player'),participant('P-INTRUDER','affected','tax.entity.agent.intruder')],'may',
    [condition('C-DUCK','all',[{'predicate':'P-ORIGINAL-TARGET would be Attacked by P-INTRUDER'},{'predicate':'same Room contains at least one other Character'}],['SA-DUCK-1'])],
    [decision('D-USE-REACTION','P-OWNER','player-choice',0,1,True,'public-on-play',['decline','play Duck and Cover'])],
    [{'informationId':'I-REACTION-CARD','subjectRef':'Duck and Cover identity','audience':'public','revealTrigger':'play','secrecy':'hidden in hand before play'}],[],
    [{'targetId':'T-OTHER-CHARACTER','selectorRef':'unresolved-by-source-when-multiple','eligibleTaxonIds':['tax.entity.agent.character'],'cardinality':{'min':1,'max':1},'selectionMode':'unresolved-when-multiple','visibility':'public'}],
    [operation('S01',1,'play-card','may','P-OWNER','Duck and Cover',['SA-DUCK-1','SA-DUCK-2'],decision_ref='D-USE-REACTION'),operation('S02',2,'replace-target','must','P-INTRUDER','T-OTHER-CHARACTER',['SA-DUCK-1'],conditions=['Reaction played'],target_ref='T-OTHER-CHARACTER'),operation('S03',3,'invoke-process','must','P-INTRUDER','Intruder Attack against replacement target',['SA-DUCK-1'],conditions=['Reaction played']),operation('S04',4,'transition-zone','must','P-OWNER','Duck and Cover card',['SA-DUCK-2'],conditions=['Reaction played'],transition={'from':'tax.scaffold.zone.hand','to':'tax.scaffold.zone.discard-pile'})],
    {'policy':'replacement-effect','unit':'one pending Attack','onImpossible':'source does not specify replacement selection when multiple other Characters exist'}, {'kind':'one-pending-attack'}, {'policy':'one Reaction card play per copy'}, [], ['SEM-Q-001'], []))

records.append(record(
    'SEM-ROOM-01','Sprinklers Control Room effect','source-backed','component-effect','official-component-reference','verbatim-structure',
    [assertion('SA-ROOM01-1','SRC-ROOM-HELP','entry 01 SPRINKLERS CONTROL',['decisions','targets','operations'],'Discard all [R01-I04]\nfrom a chosen Section.','docs/rules/source-extraction/room-help-sheet.json:01.printedEffect')],
    ['term.section','icon.fire'],['tax.entity.spatial.section','tax.entity.component.marker.fire'],['NI-0447'],
    timing('TW-ROOM01','tax.process.action.use-room','when-triggered','per-invoked-Room-effect'),[participant('P-ACTIVE-PLAYER','decision-owner','tax.entity.agent.player'),participant('P-ACTIVE-CHARACTER','actor','tax.entity.agent.character')],'must',
    [condition('C-ROOM01','predicate',[{'predicate':'invoked Sprinklers Control effect is fully resolvable'}],['SA-ROOM01-1'])],
    [decision('D-SECTION','P-ACTIVE-PLAYER','player-choice',1,1,False,'public-on-declaration',['Section A','Section B','Section C'])],
    [{'informationId':'I-ROOM01','subjectRef':'selected Section and Fire markers','audience':'public','revealTrigger':'declaration','secrecy':'none'}],[],
    [{'targetId':'T-SECTION','selectorRef':'P-ACTIVE-PLAYER','eligibleTaxonIds':['tax.entity.spatial.section'],'cardinality':{'min':1,'max':1},'selectionMode':'player-choice','visibility':'public'}],
    [operation('S01',1,'select-target','must','P-ACTIVE-PLAYER','one Section',['SA-ROOM01-1'],decision_ref='D-SECTION',target_ref='T-SECTION'),operation('S02',2,'remove-component','must','rules-system','all Fire markers in selected Section',['SA-ROOM01-1'],target_ref='T-SECTION',repeat={'scope':'all matching markers'})],
    {'policy':'all-or-nothing-selection','unit':'Room effect','onImpossible':'parent Use Room Action may be selected only if this effect is fully resolvable'}, {'kind':'instantaneous-room-effect'}, {'policy':'repeatable only through distinct legal invocations; invocation source controls any Action cost'}, [], [], []))
records[-1]['sourceAssertions'][0]['textKind']='verbatim'

records.append(record(
    'SEM-ENDGAME-001','End-of-game triggers and checks','source-backed-with-open-question','endgame','official-errata','open-alternatives',
    [assertion('SA-END-1','SRC-RULEBOOK','printed page 39 / lines 6238–6273',['preconditions','operations','outcomes','unresolvedQuestionRefs'],'Game ends at Round 14, when all players are dead/Escaped/Hibernated, or Facility destruction; then resolve Infection, Eclosion, Objective reveal/check, and winners.','docs/rules/03-intruders-and-survival.md:INT-011'),assertion('SA-END-2','SRC-FAQ','General rules #3',['operations'],'Pending Autodestruction happens before the endgame sequence.','docs/rules/03-intruders-and-survival.md:INT-010')],
    ['term.end-of-the-game','term.infection-procedure','term.eclosion-procedure','term.objective','term.fulfilled','term.survivor'],['tax.process.procedure.endgame','tax.process.procedure.infection','tax.process.procedure.eclosion','tax.entity.information.objective','tax.state.objective.fulfilled','tax.state.participation.survivor'],[],
    timing('TW-ENDGAME','tax.process.procedure.endgame','when-triggered','once-per-game'),[participant('P-RULES','rules-system'),participant('P-CHARACTERS','collection','tax.entity.agent.character'),participant('P-PLAYERS','collection','tax.entity.agent.player')],'must',
    [condition('C-END-TRIGGER','any',[{'predicate':'Round 14 ends'},{'predicate':'all players died, Escaped, or Hibernated'},{'predicate':'Facility is Destroyed'}],['SA-END-1'])],
    [decision('D-LATE-OBJECTIVE','P-PLAYERS','player-choice',1,1,False,'owner-private-until-reveal',['each still-alive eligible Player chooses from their two Objective cards'])],
    [{'informationId':'I-OBJECTIVES','subjectRef':'unselected/chosen Objective identities','audience':'owner-private','revealTrigger':'endgame Objective check','secrecy':'hidden until reveal'},{'informationId':'I-END-RESULT','subjectRef':'survival and winners','audience':'public','revealTrigger':'resolution','secrecy':'none'}],[],[],
    [operation('S01',1,'invoke-process','if-able','rules-system','pending Autodestruction',['SA-END-2']),operation('S02',2,'set-state','if-able','onboard Characters at Round-14 expiry','sem.state.participation.dead',['SA-END-1'],conditions=['Round 14 trigger']),operation('S03',3,'invoke-process','must','each alive Escaped/Hibernated Character without Larva','Infection Procedure',['SA-END-1'],invoke='SEM-INFECTION-PROCEDURE-001'),operation('S04',4,'invoke-process','must','each alive Escaped/Hibernated Character currently with Larva','Eclosion Procedure',['SA-END-1'],invoke='SEM-ECLOSION-PROCEDURE-001',notes='Whether “currently” includes a Larva gained in S03 is OQ-002.'),operation('S05',5,'choose','if-able','each still-alive Player lacking chosen Objective','one Objective',['SA-END-1'],decision_ref='D-LATE-OBJECTIVE'),operation('S06',6,'reveal','must','each still-alive Character','chosen Objective',['SA-END-1']),operation('S07',7,'evaluate-condition','must','each still-alive Character','Objective fulfilled',['SA-END-1']),operation('S08',8,'set-state','if-able','Character with fulfilled Objective','sem.state.outcome.winner',['SA-END-1'])],
    {'policy':'ordered-complete','unit':'endgame sequence step','onImpossible':'source-specific; unresolved iteration questions remain explicit'}, {'kind':'end-of-game'}, {'policy':'once per game'}, [{'condition':'Character remains alive and chosen Objective is Fulfilled','result':'wins'}], ['OQ-001','OQ-002'], []))

records.extend(build_general_records(record, assertion, timing, participant, condition, decision, operation, EVENT_RULE_IDS, ATTACK_RULE_IDS))
records.extend(build_intruder_help_records(REPO, record, assertion, timing, participant, condition, operation))
records.extend(build_room_records(REPO, record, assertion, timing, participant, condition, decision, operation))
records.extend(build_robot_records(REPO, robot_source_index, record, assertion, timing, participant, condition, decision, operation, EXPLORATION_RULE_IDS, [f'SEM-ROOM-{index:02d}' for index in range(1, 26)]))
records.extend(build_event_records(REPO, event_source_index, record, assertion, timing, participant, condition, decision, operation))
records.extend(build_exploration_records(REPO, exploration_source_index, record, assertion, timing, participant, condition, decision, operation))
records.extend(build_attack_records(REPO, attack_source_index, record, assertion, timing, participant, condition, operation))
records.sort(key=lambda item: item['ruleId'])

semantic_questions = {
    'schemaVersion':1,'recordType':'semantic-review-gates','status':'pilot built with deferred questions and explicit alternatives; no default answer adopted',
    'counts':{'questions':30,'officialClarificationPreferred':7,'sourceAmbiguitiesIntroducedByPilot':23,'resolved':0,'open':30},
    'questions':[
        {'questionId':'OQ-001','title':'Eclosion existing-hand behavior','decisionClass':'official-clarification-preferred','blocksRuleIds':['SEM-ENDGAME-001','SEM-ECLOSION-PROCEDURE-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/open-questions.md:OQ-001'],'alternatives':[{'alternativeId':'OQ-001-A','description':'Check all cards in hand after drawing, including pre-existing cards.','support':'literal “in hand” wording'},{'alternativeId':'OQ-001-B','description':'Check only the four newly drawn cards.','support':'possible procedure intent; not stated'}]},
        {'questionId':'OQ-002','title':'Endgame Larva iteration timing','decisionClass':'official-clarification-preferred','blocksRuleIds':['SEM-ENDGAME-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/open-questions.md:OQ-002'],'alternatives':[{'alternativeId':'OQ-002-A','description':'Evaluate “currently has a Larva” when the Eclosion cohort step is reached, including Larvae gained in the preceding Infection step.','support':'sequential text and “during this Sequence” note'},{'alternativeId':'OQ-002-B','description':'Snapshot Larva status at the start of endgame.','support':'possible cohort-intent reading; not explicit'}]},
        {'questionId':'OQ-003','title':'Starting Player token passing over nonparticipants','decisionClass':'official-clarification-preferred','blocksRuleIds':['SEM-RT-012'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/open-questions.md:OQ-003'],'alternatives':[{'alternativeId':'OQ-003-A','description':'Skip dead/Escaped/Hibernated participants and assign the role to the next eligible Player.','support':'natural reading of “no longer takes part”'},{'alternativeId':'OQ-003-B','description':'Move the token to the next seat/Player regardless of participation status.','support':'literal clockwise-next reading; downstream effect unclear'}]},
        {'questionId':'OQ-004','title':'Player Phase recalculation after mid-Turn death','decisionClass':'official-clarification-preferred','blocksRuleIds':['SEM-RT-005'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/open-questions.md:OQ-004'],'alternatives':[{'alternativeId':'OQ-004-A','description':'End the dead Character’s Action window and continue with the next eligible Player/Turn.','support':'dead Character no longer takes part'},{'alternativeId':'OQ-004-B','description':'Apply another phase-advancement procedure.','support':'source does not specify one'}]},
        {'questionId':'OQ-007','title':'Secure tokens and simultaneous multi-Intruder entry','decisionClass':'official-clarification-preferred','blocksRuleIds':['SEM-SECURE-ENTRY-001','SEM-EVENT-EGG-PROTECTION-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/open-questions.md:OQ-007'],'alternatives':[{'alternativeId':'OQ-007-A','description':'Each entering Intruder consumes one Secure token and prevents its own entry Attack.','support':'per-Intruder “whenever an Intruder enters” wording'},{'alternativeId':'OQ-007-B','description':'One Secure token prevents all Attacks from one simultaneous group entry.','support':'possible simultaneous-effect grouping; no example'}]},
        {'questionId':'OQ-009','title':'Nest placement before discovery','decisionClass':'official-clarification-preferred','blocksRuleIds':['SEM-EVENT-HATCHING-001','SEM-EVENT-EGG-PROTECTION-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/open-questions.md:OQ-009'],'alternatives':[{'alternativeId':'OQ-009-A','description':'Reserve/defer the placed Intruder until the Nest appears.','support':'possible physical hidden-space treatment; no checked rule'},{'alternativeId':'OQ-009-B','description':'Ignore the impossible Nest-placement sentence and continue the Event.','support':'general Event impossible-sentence rule'},{'alternativeId':'OQ-009-C','description':'Use another physical hidden-Nest procedure.','support':'source procedure not recovered'}]},
        {'questionId':'SEM-Q-001','title':'Duck and Cover replacement target when multiple other Characters share the Room','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-REACTION-DUCK-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['assets/tts-mod/extract/v2-dl/tree/cards/character/contractor-026.jpg'],'alternatives':[{'alternativeId':'SEM-Q-001-A','description':'Reaction owner chooses one other Character.','support':'effect owner often owns choices, but this card does not say choose'},{'alternativeId':'SEM-Q-001-B','description':'Apply ordinary Intruder target priority among the other Characters.','support':'general attack targeting, but replacement wording may override'},{'alternativeId':'SEM-Q-001-C','description':'Another tie-break applies.','support':'not stated'}]},
        {'questionId':'SEM-Q-002','title':'Exploratory Movement Noise when the Entrance Effect is itself a Noise roll','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ACT-EXPLORE-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 4528–4530, 4702–4705, 4753–4760','docs/rules/open-questions.md:SEM-Q-002'],'alternatives':[{'alternativeId':'SEM-Q-002-A','description':'The Entrance-Effect Noise roll satisfies the universal post-Movement Noise requirement; perform one roll total.','support':'worked example resolves one Entrance Noise and then finishes; licensed BGA Beta replay release 260617-1110 shows one roll for a Noise Entrance effect and no automatic roll after a non-Noise Entrance effect, but this is secondary implementation evidence rather than an official ruling'},{'alternativeId':'SEM-Q-002-B','description':'Perform the universal Movement Noise plus the additional Entrance-Effect Noise; perform two rolls.','support':'Entrance Effect is called additional and Noise is mandatory after every Movement'}]},
        {'questionId':'SEM-Q-003','title':'Opportunity Attack selection when more than three equal-largest Intruders qualify','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ACT-MOVE-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 4551–4557'],'alternatives':[{'alternativeId':'SEM-Q-003-A','description':'Acting Player chooses which equal-largest Intruders attack.','support':'possible player-owned target selection; not stated'},{'alternativeId':'SEM-Q-003-B','description':'Use a deterministic map/turn-order tie-break.','support':'other rule families use deterministic ties; none cited here'},{'alternativeId':'SEM-Q-003-C','description':'Resolve another source-defined physical ordering.','support':'not recovered'}]},
        {'questionId':'SEM-Q-004','title':'Supply Room “You may keep 2” cardinality','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ROOM-04'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/source-extraction/room-help-sheet.json:04.printedEffect'],'alternatives':[{'alternativeId':'SEM-Q-004-A','description':'If the player keeps Items, they keep exactly 2; “may” permits declining the keep.','support':'optional exact-number reading of “You may keep 2”'},{'alternativeId':'SEM-Q-004-B','description':'The player may keep any subset from zero through 2.','support':'common up-to-number reading; not explicitly written'}]},
        {'questionId':'SEM-Q-005','title':'Drilling Station new-Corridor endpoint selection','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ROOM-17'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/source-extraction/room-help-sheet.json:17.printedEffect','docs/rules/source-extraction/room-help-sheet.json:17.associatedNotes[0]'],'alternatives':[{'alternativeId':'SEM-Q-005-A','description':'Player chooses a legal edge/end point from the Room with the Robot.','support':'digital adaptation needed if multiple legal edges exist; not named by source'},{'alternativeId':'SEM-Q-005-B','description':'Use a physical-game placement procedure or deterministic edge rule.','support':'source says leading from the Room but gives no selector/tie-break'}]},
        {'questionId':'SEM-Q-006','title':'Leaving the Shell white-rectangle glyph identity','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-EVENT-LEAVING-THE-SHELL-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['assets/tts-mod/extract/v2-dl/tree/cards/game/event-054.png','assets/tts-mod/extract/selected-card-text-evidence.json','docs/rules/source-extraction/secondary/bga-staticData-260622-1220.js'],'alternatives':[{'alternativeId':'SEM-Q-006-A','description':'Treat all three white rectangles as Action-card denotations, following the licensed-digital occurrence.','support':'EVENT_CARDS_DATA.Event_LeavingTheShell names ACTION-CARD in all three positions; secondary only'},{'alternativeId':'SEM-Q-006-B','description':'Retain the three source-local glyphs without a semantic card identity until current official component evidence is obtained.','support':'direct pixel comparison found featureless rectangles with no authoritative canonical match'},{'alternativeId':'SEM-Q-006-C','description':'Apply another source-local card-type identity established by future official evidence.','support':'the scan morphology does not discriminate a current glossary token'}]},
        {'questionId':'SEM-Q-007','title':'Finite Intruder allocation across multiple Event target spaces','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-EVENT-NO-WAY-OUT-001','SEM-EVENT-HATCHING-001','SEM-EVENT-EGG-PROTECTION-001','SEM-EVENT-OVERWHELMING-ENEMIES-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 5189–5198, 5298–5355','docs/rules/semantics/event-source-index.json'],'alternatives':[{'alternativeId':'SEM-Q-007-A','description':'Allocate limited models by Facility top-left row order.','support':'Event movement and Noise effects use spatial orders, but no placement-order extension is stated'},{'alternativeId':'SEM-Q-007-B','description':'An affected/active player chooses which eligible spaces receive the limited models.','support':'could resolve physical scarcity, but no decision owner is named'},{'alternativeId':'SEM-Q-007-C','description':'Use another simultaneous or physical allocation procedure.','support':'the limited-model rule says place as many as possible but gives no multi-space tie-break'}]},
        {'questionId':'SEM-Q-008','title':'Finite Malfunction allocation and fallback order across Event target Rooms','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-EVENT-SYSTEM-FAILURE-001','SEM-EVENT-DAMAGE-001','SEM-EVENT-LIFE-SUPPORT-FAILURE-001','SEM-EVENT-DAMAGING-FIRE-001','SEM-EVENT-GENERATORS-OVERHEAT-001','SEM-EVENT-REACTOR-OVERHEATING-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 3269–3299, 4368–4375, 4414–4426','docs/rules/semantics/event-source-index.json'],'alternatives':[{'alternativeId':'SEM-Q-008-A','description':'Resolve eligible Rooms top-left row by row, spending remaining Malfunctions and then applying Fire fallback.','support':'a deterministic spatial order exists for Noise effects, not for these marker placements'},{'alternativeId':'SEM-Q-008-B','description':'Treat the whole multi-Room printed sentence as simultaneous and apply one source-defined aggregate fallback.','support':'Event impossibility is sentence-scoped, but no aggregate finite-pool rule is stated'},{'alternativeId':'SEM-Q-008-C','description':'A player chooses which eligible Rooms receive remaining Malfunctions versus fallback Fire.','support':'would allocate scarcity but no decision owner is named'}]},
        {'questionId':'SEM-Q-009','title':'Fire-spread source snapshot versus propagation during one Event sentence','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-FIRE-SPREAD-001','SEM-EVENT-FIRE-BREATH-001','SEM-EVENT-DAMAGING-FIRE-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 4284–4287, 4436–4456','assets/tts-mod/extract/v2-dl/tree/cards/game/event-052.png','assets/tts-mod/extract/v2-dl/tree/cards/game/event-167.png'],'alternatives':[{'alternativeId':'SEM-Q-009-A','description':'Snapshot source Rooms containing Fire when the printed spread sentence begins.','support':'bounded reading of “From each Room with Fire”'},{'alternativeId':'SEM-Q-009-B','description':'A newly placed Fire becomes another source during the same sentence and may propagate further.','support':'literal state can satisfy “Room with Fire” after placement; no stop rule is stated'},{'alternativeId':'SEM-Q-009-C','description':'Use another source-defined simultaneous spread procedure.','support':'no checked ordering/snapshot procedure was recovered'}]},
        {'questionId':'SEM-Q-010','title':'Robot Malfunction effect-availability contradiction','decisionClass':'official-clarification-preferred','blocksRuleIds':['SEM-ROBOT-MALFUNCTION-001','SEM-ROBOT-MALFUNCTION-PLACEMENT-001','SEM-EVENT-RISE-OF-THE-MACHINE-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 4383–4391, 6015–6022','assets/tts-mod/extract/v2-dl/tree/cards/game/event-166.jpg'],'alternatives':[{'alternativeId':'SEM-Q-010-A','description':'Page 22 controls: effects that only require a Robot remain available, and a repeated Robot Malfunction placement is ignored.','support':'specific Malfunction-on-Robot passage on page 22'},{'alternativeId':'SEM-Q-010-B','description':'Page 37 controls: all game effects mentioning a malfunctioned Robot are unavailable.','support':'later Robot-specific passage on page 37'},{'alternativeId':'SEM-Q-010-C','description':'Harmonize by distinguishing using Robot text/Actions from external effects that merely locate or require the Robot.','support':'possible scoped reading, but the source does not state the boundary'}]},
        {'questionId':'SEM-Q-011','title':'Exploration multi-slot Corridor draw and finite-component allocation order','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':EXPLORATION_RULE_IDS,'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 3538–3548, 4502–4522','docs/rules/semantics/exploration-source-index.json'],'alternatives':[{'alternativeId':'SEM-Q-011-A','description':'The exploring player assigns each random Corridor draw and each last available finite component to one eligible source-local slot.','support':'physical handling could permit player placement, but the source names no decision owner'},{'alternativeId':'SEM-Q-011-B','description':'Use a fixed source-local spatial order anchored to the printed North orientation for Corridor draws and scarce components.','support':'the card has a North orientation and exact slots, but no clockwise/counterclockwise/start-slot rule is stated'},{'alternativeId':'SEM-Q-011-C','description':'Randomly assign drawn Corridors and scarce components among the remaining eligible source-local slots.','support':'Corridor identity is random, but the source does not extend randomness to slot assignment'}]},
        {'questionId':'SEM-Q-012','title':'Unrevealed Robot and non-Activation effects','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ROBOT-REVEAL-001','SEM-ROBOT-MALFUNCTION-PLACEMENT-001','SEM-EVENT-RISE-OF-THE-MACHINE-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 2421–2426, 2446–2448, 4383–4391, 5982–5996','docs/rules/semantics/robot-source-index.json'],'alternatives':[{'alternativeId':'SEM-Q-012-A','description':'Before reveal, printed Robot actions/text remain inaccessible but external effects that need only the physical Robot/card may resolve without inspection.','support':'card is face down and Activation is barred; page 22 distinguishes effects that only require a Robot'},{'alternativeId':'SEM-Q-012-B','description':'All Robot-referencing effects are unavailable until the reveal trigger.','support':'possible extension of pre-reveal Activation unavailability; not stated'},{'alternativeId':'SEM-Q-012-C','description':'A source-specific external effect may reveal or inspect the face before the normal trigger.','support':'no checked base source grants that access'}]},
        {'questionId':'SEM-Q-013','title':'Robot movement destination owner and multi-step route timing','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ROBOT-MOVEMENT-001',*ROBOT_RULE_IDS],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 6023–6032','docs/rules/semantics/robot-source-index.json'],'alternatives':[{'alternativeId':'SEM-Q-013-A','description':'The activating player selects each legal neighboring destination as each step is reached and may stop at zero through the printed maximum.','support':'movement comes from player Actions and the faces say up to; selection timing is not explicit'},{'alternativeId':'SEM-Q-013-B','description':'The activating player commits the complete route when choosing the movement option.','support':'possible single-effect resolution; not stated'},{'alternativeId':'SEM-Q-013-C','description':'Another source-defined owner or worst-case physical resolution selects destinations.','support':'Golden Rule supplies a physical worst-case fallback but no deterministic target/tie-break suitable as a silent default'}]},
        {'questionId':'SEM-Q-014','title':'Exploration Robot Noise modality and timing','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ROBOT-EXPLORATION-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 6023–6032','assets/tts-mod/extract/v2-dl/tree/cards/game/robotDeck-004.jpg'],'alternatives':[{'alternativeId':'SEM-Q-014-A','description':'After the Robot explores, resolve one mandatory post-Movement Noise roll despite ignored Entrance Effects.','support':'the Exploration Robot is the sole no-Noise exception and “could make” may describe this case'},{'alternativeId':'SEM-Q-014-B','description':'Resolve no Noise because the Robot normally never rolls Noise and the card suppresses the Entrance Effect.','support':'the exception wording is permissive rather than mandatory'},{'alternativeId':'SEM-Q-014-C','description':'Resolve Noise only when another source-specific part of the selected Exploration occurrence requires it.','support':'possible scoped meaning of “could”; no timing rule recovered'}]},
        {'questionId':'SEM-Q-015','title':'Medical Robot branch and reduced-restoration decision owner','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ROBOT-MEDICAL-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 3797–3813','assets/tts-mod/extract/v2-dl/tree/cards/game/robotDeck-130.jpg'],'alternatives':[{'alternativeId':'SEM-Q-015-A','description':'The activating player chooses the target and discard-versus-restore branch; the target owner chooses the Wound and restoration amount.','support':'face explicitly gives “your choice” only for the Character; general health rules give affected player choices'},{'alternativeId':'SEM-Q-015-B','description':'The targeted Character’s player chooses the branch as well as Wound/restoration amount.','support':'the target resolves “discards ... or restores”; branch owner is not explicit'},{'alternativeId':'SEM-Q-015-C','description':'The activating player owns every choice.','support':'possible effect-owner reading; conflicts with ordinary affected-player health choices'}]},
        {'questionId':'SEM-Q-016','title':'Securing Robot accessible Door eligibility','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ROBOT-SECURING-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['assets/tts-mod/extract/v2-dl/tree/cards/game/robotDeck-173.jpg','docs/rulebooks/rulebook_text.txt:lines 4243–4287, 6023–6032'],'alternatives':[{'alternativeId':'SEM-Q-016-A','description':'Eligible Doors are Door slots directly touching the Robot’s current Room.','support':'local physical access reading; “accessible” is not defined'},{'alternativeId':'SEM-Q-016-B','description':'Eligible Doors include another source-defined nearby/reachable set.','support':'the word accessible may be broader than touching; no range is stated'},{'alternativeId':'SEM-Q-016-C','description':'Apply the ordinary local-effect rule from the activating Character’s Room.','support':'general default exists, but the face explicitly anchors access to the Robot instead'}]},
        {'questionId':'SEM-Q-017','title':'Securing Robot exact-two Secure placement under scarcity/capacity','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ROBOT-SECURING-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rulebooks/rulebook_text.txt:lines 3187–3198, 3543–3548, 4396–4405','assets/tts-mod/extract/v2-dl/tree/cards/game/robotDeck-173.jpg'],'alternatives':[{'alternativeId':'SEM-Q-017-A','description':'The option is selectable only when exactly 2 Secure tokens can be placed within supply and Room capacity.','support':'chosen effects must resolve entirely'},{'alternativeId':'SEM-Q-017-B','description':'Place available tokens sequentially and let each unavailable placement do nothing under Component Limits.','support':'generic unavailable components do nothing; quantity grouping is unspecified'},{'alternativeId':'SEM-Q-017-C','description':'If both cannot be placed, the complete placement instruction does nothing.','support':'possible whole-instruction reading of Component Limits'}]},
        {'questionId':'SEM-Q-018','title':'Server Robot Room-effect actor, costs, and local context','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ROBOT-SERVER-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['assets/tts-mod/extract/v2-dl/tree/cards/game/robotDeck-068.jpg','docs/rulebooks/rulebook_text.txt:lines 3187–3198, 3537–3542, 5982–6041'],'alternatives':[{'alternativeId':'SEM-Q-018-A','description':'The activating player resolves the Robot Room’s printed effect using the activating Character for “you” predicates, with no second Basic-Action cost and only the Room Malfunction restriction bypassed.','support':'Robot option is already the selected effect; actor substitution is not stated'},{'alternativeId':'SEM-Q-018-B','description':'The Robot is the local acting entity and the activating player owns choices, so Character-specific predicates may be unavailable.','support':'face anchors the Room to the Robot'},{'alternativeId':'SEM-Q-018-C','description':'Invoke the complete Use the Room Basic Action except for the printed Malfunction override.','support':'literal “use the Room” wording; would add cost/restrictions not printed on the Robot face'}]},
        {'questionId':'SEM-Q-019','title':'Technical Robot Malfunction-removal target scope','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':['SEM-ROBOT-TECHNICAL-001'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['assets/tts-mod/extract/v2-dl/tree/cards/game/robotDeck-137.jpg','docs/rulebooks/rulebook_text.txt:lines 3537–3542, 4392–4395'],'alternatives':[{'alternativeId':'SEM-Q-019-A','description':'“From the Room” targets only a marker physically on the Room component; Fire has the same scope.','support':'face names the Room rather than an object in it'},{'alternativeId':'SEM-Q-019-B','description':'The general discard-Malfunction rule permits a marker on the Room, an Item, or the Robot in that Room, while Fire remains on the Room.','support':'page 22 broadens local discard-Malfunction effects unless stated otherwise'},{'alternativeId':'SEM-Q-019-C','description':'Another target owner/scope applies because the activating Character may be remote.','support':'general local effects anchor to a Character, but this face explicitly anchors to the Robot Room'}]},
        {'questionId':'SEM-Q-020','title':'Fury Character scope omitted by the TTS scan','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':ATTACK_QUESTION_BLOCKS['SEM-Q-020'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/semantics/attack-source-index.json','docs/rules/open-questions.md:SEM-Q-020'],'alternatives':[{'alternativeId':'SEM-Q-020-A','description':'Apply both Fury cohorts to all Characters in the game, following the scan’s unqualified “All Characters.”','support':'literal source-bound TTS wording'},{'alternativeId':'SEM-Q-020-B','description':'Apply both cohorts only in the attacking Intruder’s Room, following the licensed record.','support':'licensed INTRUDER_ATTACKS_DATA explicitly says “in your Room”; secondary only'},{'alternativeId':'SEM-Q-020-C','description':'Apply another source-defined local-effect scope.','support':'the general local-effect rule is Character-actor framed and does not clearly name an Intruder Attack actor/context'}]},
        {'questionId':'SEM-Q-021','title':'Compound Attack effects after an intermediate Character death','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':ATTACK_QUESTION_BLOCKS['SEM-Q-021'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/semantics/attack-source-index.json','docs/rules/open-questions.md:SEM-Q-021'],'alternatives':[{'alternativeId':'SEM-Q-021-A','description':'Stop later Character-bound operations in the selected panel when an earlier Health/Wound operation kills that Character.','support':'a dead Character no longer participates, but no Attack-card continuation sentence states this'},{'alternativeId':'SEM-Q-021-B','description':'Complete every remaining printed operation in the selected panel even after death, including later Contamination/Wound instructions.','support':'standard Attacks say resolve the associated effect before discarding; no explicit stop-on-death rule'},{'alternativeId':'SEM-Q-021-C','description':'Treat coordinated Wound/Contamination outcomes as simultaneous before applying death.','support':'some faces use “and,” but no simultaneous-resolution procedure is supplied'}]},
        {'questionId':'SEM-Q-022','title':'Blood Sense Movement check and relocation after death/interruption','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':ATTACK_QUESTION_BLOCKS['SEM-Q-022'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/semantics/attack-source-index.json','docs/rules/open-questions.md:SEM-Q-022'],'alternatives':[{'alternativeId':'SEM-Q-022-A','description':'Evaluate “If you are Moving” when Blood Sense is resolved and relocate the attacker to the already selected Movement destination even if the target dies before arriving.','support':'literal future destination wording; death consequence is not addressed'},{'alternativeId':'SEM-Q-022-B','description':'Relocate only if the target remains alive and completes Movement to the selected destination.','support':'“where your Movement ends” may require an actually completed Movement'},{'alternativeId':'SEM-Q-022-C','description':'Use another destination or cancellation rule when death/interruption ends Movement early.','support':'no checked source names one'}]},
        {'questionId':'SEM-Q-023','title':'Deadly Claws random Wound assignment and finite order','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':ATTACK_QUESTION_BLOCKS['SEM-Q-023'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/semantics/attack-source-index.json','docs/rules/open-questions.md:SEM-Q-023'],'alternatives':[{'alternativeId':'SEM-Q-023-A','description':'Fill eligible slots from left to right with sequential random Wound draws, then resolve the final additional Wound.','support':'physical track order is visually available, but the card does not state an assignment direction'},{'alternativeId':'SEM-Q-023-B','description':'Randomly assign drawn Wounds among the eligible slots before the final additional Wound.','support':'Wound identities are random, but slot assignment randomization is not stated'},{'alternativeId':'SEM-Q-023-C','description':'Apply another source-defined simultaneous/physical assignment, including finite-deck exhaustion handling.','support':'no owner, tie-break, or shortage order is printed'}]},
        {'questionId':'SEM-Q-024','title':'MISS applicability with no printed Intruder-type badges','decisionClass':'source-ambiguity-owner-decision-after-source-search','blocksRuleIds':ATTACK_QUESTION_BLOCKS['SEM-Q-024'],'plannedRuleIds':[],'defaultProhibited':True,'sourceEvidenceRefs':['docs/rules/semantics/attack-source-index.json','docs/rules/open-questions.md:SEM-Q-024'],'alternatives':[{'alternativeId':'SEM-Q-024-A','description':'A no-badge MISS panel applies universally to Adult, Drone, and Queen Attacks.','support':'licensed record explicitly lists all three types; scan layout likely uses omission as universal, but no checked official convention says so'},{'alternativeId':'SEM-Q-024-B','description':'No matching badge means no associated effect; the scan card is discarded without reshuffling.','support':'official Standard Attacks instruct finding a matching type icon'},{'alternativeId':'SEM-Q-024-C','description':'Another source-local universal-applicability convention applies.','support':'the face visibly has text but no printed badge or explanatory marker'}]},
    ],
}


contradictions = {
    'schemaVersion': 1,
    'recordType': 'semantic-conflict-register',
    'policy': 'Readable source differences remain separate. Authority may resolve a general rule without rewriting lower-authority component wording; unresolved conflicts never receive a default.',
    'counts': {'conflicts': 18, 'resolvedByAuthority': 8, 'unresolved': 8, 'preservedBoundary': 2},
    'conflicts': [
        {'conflictId':'SC-001','title':'Search keep optionality and unchosen destination','status':'resolved-by-authority','questionId':None,'affectedRuleIds':['SEM-ACT-SEARCH-001'],'evidenceRefs':['SRC-RULEBOOK','SRC-CARD-SEARCH-MEDICAL'],'difference':'Card says may keep 1 / discard the rest; rulebook says pick 1, put unchosen cards on respective deck bottoms, and do not reveal them.','resolution':'Official-primary rulebook controls the general Search procedure; exact card wording remains a source variant.'},
        {'conflictId':'SC-002','title':'Rest Uninfected/non-Infected wording and destination','status':'resolved-by-authority','questionId':None,'affectedRuleIds':['SEM-ACT-REST-001'],'evidenceRefs':['SRC-RULEBOOK','SRC-CARD-REST','SRC-CARD-REST-MEDICAL'],'difference':'Reviewed face says remove all Uninfected; Medical Support variant says remove non-Infected instead of discarding; ordinary Infection Procedure discards all Contaminations.','resolution':'Each component variant is retained. Pilot composes the reviewed face as a destination override over the official Procedure.'},
        {'conflictId':'SC-003','title':'Exploration Entrance Noise versus universal Movement Noise','status':'unresolved','questionId':'SEM-Q-002','affectedRuleIds':['SEM-ACT-EXPLORE-001','SEM-ACT-MOVE-001'],'evidenceRefs':['SRC-RULEBOOK','docs/rules/open-questions.md:SEM-Q-002'],'difference':'Noise is mandatory after every Movement; Entrance Effect is called additional; the worked example resolves one Entrance Noise and then finishes.','resolution':'No default; BGA Beta replay release 260617-1110 is a licensed-digital strong lead for alternative A, but FAQ v1.2 does not resolve the official wording conflict.'},
        {'conflictId':'SC-004','title':'Duck and Cover multiple replacement targets','status':'unresolved','questionId':'SEM-Q-001','affectedRuleIds':['SEM-REACTION-DUCK-001'],'evidenceRefs':['SRC-CARD-DUCK','SRC-RULEBOOK'],'difference':'Card says the other Character but gives no selection/tie-break when more than one other Character is present.','resolution':'No default; explicit alternatives in review-gates.json.'},
        {'conflictId':'SC-005','title':'Event placement at an undiscovered Nest','status':'unresolved','questionId':'OQ-009','affectedRuleIds':['SEM-EVENT-HATCHING-001','SEM-EVENT-EGG-PROTECTION-001'],'evidenceRefs':['SRC-EVENT-HATCHING','SRC-EVENT-5617','SRC-RULEBOOK'],'difference':'Events require placement in the Nest; checked sources do not define placement when the Nest Room is absent.','resolution':'No default; Event impossible-sentence rule is one candidate, not silently adopted.'},
        {'conflictId':'SC-006','title':'Player Help phase sequence versus current rulebook','status':'preserved-boundary','questionId':None,'affectedRuleIds':['SEM-RT-001'],'evidenceRefs':['docs/rules/source-extraction/player-help-source-extraction.json','SRC-RULEBOOK'],'difference':'TTS Player Help fronts encode an obsolete phase sequence and 10-card count while the official current rulebook controls base sequence/count.','resolution':'Retain TTS as source-version evidence; never alias same words to current semantics.'},
        {'conflictId':'SC-007','title':'FACILITY RESTART unreadable exact-source span','status':'preserved-boundary','questionId':None,'affectedRuleIds':[],'evidenceRefs':['docs/rules/source-extraction/card-gap-inventory.json'],'difference':'Prototype exact source ends “Systems must be” with no recoverable following mark; other variants differ materially.','resolution':'Keep source blocked; no semantic record may invent or borrow the missing mark.'},
        {'conflictId':'SC-008','title':'Supply Room optional keep cardinality','status':'unresolved','questionId':'SEM-Q-004','affectedRuleIds':['SEM-ROOM-04'],'evidenceRefs':['SRC-ROOM-HELP'],'difference':'Printed “You may keep 2” does not unambiguously state optional exact-two versus any subset up to two.','resolution':'No default; explicit alternatives in review-gates.json.'},
        {'conflictId':'SC-009','title':'Leaving the Shell source glyphs versus licensed semantic placeholders','status':'unresolved','questionId':'SEM-Q-006','affectedRuleIds':['SEM-EVENT-LEAVING-THE-SHELL-001'],'evidenceRefs':['SRC-EVENT-5614','SRC-BGA-EVENTS','assets/tts-mod/extract/selected-card-text-evidence.json'],'difference':'The component scan preserves three featureless white rectangles with explicit no-match decisions; the licensed record labels all three ACTION-CARD.','resolution':'No default; retain the literal scan and licensed semantic occurrence independently until current official component evidence resolves identity.'},
        {'conflictId':'SC-010','title':'Reactor Overheating licensed movement sentence omits its verb','status':'resolved-by-authority','questionId':None,'affectedRuleIds':['SEM-EVENT-REACTOR-OVERHEATING-001'],'evidenceRefs':['SRC-RULEBOOK','SRC-EVENT-5626','SRC-BGA-EVENTS'],'difference':'The official rulebook component occurrence and TTS scan say the three Corridor-orientation Intruders move; the BGA movement entry ends after the orientation list without “move.”','resolution':'Official/current visible component evidence and the exact scan control; preserve the BGA omission as a lower-authority variant.'},
        {'conflictId':'SC-011','title':'Robot Malfunction effect availability on rulebook pages 22 and 37','status':'unresolved','questionId':'SEM-Q-010','affectedRuleIds':['SEM-ROBOT-MALFUNCTION-001','SEM-EVENT-RISE-OF-THE-MACHINE-001'],'evidenceRefs':['SRC-RULEBOOK','SRC-EVENT-5627'],'difference':'Page 22 permits effects that only require a broken Robot and ignores repeated Robot Malfunction placement; page 37 says all game effects mentioning the broken Robot are unavailable.','resolution':'No default; both equal-authority passages and their Rise of the Machine consequence remain explicit.'},
        {'conflictId':'SC-012','title':'Current official Exploration wording versus untitled TTS face wording','status':'resolved-by-authority','questionId':None,'affectedRuleIds':['SEM-EXPLORATION-5634-001','SEM-EXPLORATION-5639-001'],'evidenceRefs':['SRC-RULEBOOK','SRC-EXPLORATION-5634','SRC-EXPLORATION-5639','SRC-BGA-EXPLORATION'],'difference':'Official visible faces spell out current Room placement and Moving Cautiously wording; the TTS faces abbreviate placement and print two source-local Secure glyph occurrences in the reminder.','resolution':'Official-primary visible wording controls the matching current occurrences; exact untitled TTS and licensed structured variants remain independently preserved.'},
        {'conflictId':'SC-013','title':'Exploration multi-slot assignment has no source-named owner or order','status':'unresolved','questionId':'SEM-Q-011','affectedRuleIds':EXPLORATION_RULE_IDS,'evidenceRefs':['SRC-RULEBOOK','docs/rules/semantics/exploration-source-index.json'],'difference':'Each face shows two to four source-local Corridor slots and some show multiple Noise/Door placements, while the rulebook says to place a random Corridor in each shown space and treats components as finite without assigning draws or scarce components among slots.','resolution':'No default; preserve exact slot sets and all alternatives in review-gates.json without inventing a player choice, spatial order, or extra randomization.'},
        {'conflictId':'SC-014','title':'Military Robot scan punctuation versus licensed occurrence','status':'resolved-by-authority','questionId':None,'affectedRuleIds':['SEM-ROBOT-MILITARY-001'],'evidenceRefs':['SRC-ROBOT-529600','SRC-BGA-ROBOTS'],'difference':'The exact TTS component scan ends the additional-effect instruction with a period after the Robot glyph; the licensed ROBOT_CARDS_DATA occurrence omits that final period.','resolution':'The source-bound component scan controls over the licensed-digital secondary occurrence; preserve both verbatim without normalizing the BGA record.'},
        {'conflictId':'SC-015','title':'Deadly Claws badge applicability and branch bodies differ by source version','status':'resolved-by-authority','questionId':None,'affectedRuleIds':['SEM-ATTACK-394906-001','SEM-ATTACK-394907-001','SEM-ATTACK-394908-001'],'evidenceRefs':['SRC-RULEBOOK','SRC-ATTACK-394906','SRC-ATTACK-394907','SRC-ATTACK-394908','SRC-BGA-INTRUDER-ATTACKS'],'difference':'TTS scans assign Adult+Drone to the Health panels and Queen to a multi-Wound branch; current official-visible/licensed variants assign Adult+Queen to Health and Drone to a different injured-state branch.','resolution':'The official-visible current Lose-2 occurrence controls its matched counterpart; otherwise exact TTS and licensed variants remain occurrence-scoped under the authority order and are never flattened by title.'},
        {'conflictId':'SC-016','title':'Infecting Adult/Drone/Queen applicability differs between official and TTS','status':'resolved-by-authority','questionId':None,'affectedRuleIds':['SEM-ATTACK-394911-001'],'evidenceRefs':['SRC-RULEBOOK','SRC-ATTACK-394911','SRC-BGA-INTRUDER-ATTACKS'],'difference':'The TTS scan assigns Adult+Queen to Lose 2 and Drone to Contamination/Larva placement; official page 32 and BGA assign Adult+Drone and Queen respectively.','resolution':'Official page-32 row alignment controls the current visible counterpart. Preserve the exact TTS badge projection and licensed record as separate variants.'},
        {'conflictId':'SC-017','title':'Tail Attack Queen/Drone applicability differs between scan and licensed data','status':'resolved-by-authority','questionId':None,'affectedRuleIds':['SEM-ATTACK-394918-001','SEM-ATTACK-394919-001'],'evidenceRefs':['SRC-ATTACK-394918','SRC-ATTACK-394919','SRC-BGA-INTRUDER-ATTACKS'],'difference':'The TTS scans assign Adult+Queen to the first panel and Drone to the lethal branch; BGA assigns Adult+Drone to the first panel and Queen to the lethal branch.','resolution':'The exact source-bound scan controls over licensed-digital secondary data for these occurrences; both variants remain verbatim and source scoped.'},
        {'conflictId':'SC-018','title':'Fury scan omits the licensed attacking-Room scope','status':'unresolved','questionId':'SEM-Q-020','affectedRuleIds':['SEM-ATTACK-394909-001','SEM-ATTACK-394910-001'],'evidenceRefs':['SRC-ATTACK-394909','SRC-ATTACK-394910','SRC-BGA-INTRUDER-ATTACKS','docs/rules/open-questions.md:SEM-Q-020'],'difference':'The scans say all Heavily Injured Characters die and all survivors gain cards with no Room qualifier; BGA says those Characters are in your Room and then affects each other Character there.','resolution':'No default; preserve literal scan scope, the licensed local-scope lead, and all alternatives in review-gates.json.'},
    ],
}

pilot = {
    'schemaVersion':1,'recordType':'semantic-rule-pilot-corpus','schemaPath':'docs/rules/semantics/semantic-rule.schema.json',
    'scope':'base-game representative pilot; not full semantic coverage',
    'counts':{'records':len(records),'sourceBacked':sum(r['status']=='source-backed' for r in records),'withOpenQuestion':sum(r['status']=='source-backed-with-open-question' for r in records),'sourceVariants':sum(r['status']=='source-variant' for r in records),'sourceAssertions':sum(len(r['sourceAssertions']) for r in records),'conditions':sum(len(r['preconditions']) for r in records),'operations':sum(len(r['operations']) for r in records),'decisions':sum(len(r['decisions']) for r in records),'informationPolicies':sum(len(r['informationPolicy']) for r in records),'costs':sum(len(r['costs']) for r in records),'targets':sum(len(r['targets']) for r in records),'openQuestionReferences':sum(len(r['unresolvedQuestionRefs']) for r in records),'variantReferences':sum(len(r['sourceVariants']) for r in records)},
    'records':records,
}
coverage = {
    'schemaVersion':1,'recordType':'semantic-pilot-coverage','status':'representative pilot only',
    'systems':[
        {'system':'round/phase/turn','ruleIds':['SEM-RT-001','SEM-RT-004','SEM-RT-005','SEM-RT-007']},
        {'system':'movement/base Exploration cards','ruleIds':['SEM-ACT-MOVE-001','SEM-ACT-EXPLORE-001',*EXPLORATION_RULE_IDS]},
        {'system':'private search/zone handling','ruleIds':['SEM-ACT-SEARCH-001']},
        {'system':'infection/card modifier','ruleIds':['SEM-ACT-REST-001']},
        {'system':'reaction/replacement target','ruleIds':['SEM-REACTION-DUCK-001']},
        {'system':'Use Room and Room effects','ruleIds':['SEM-USE-ROOM-001','SEM-DATA-TOKEN-001','SEM-NEST-DESTROYED-001',*sorted(item['ruleId'] for item in records if item['ruleId'].startswith('SEM-ROOM-'))]},
        {'system':'base Event card effects','ruleIds':[ *EVENT_RULE_IDS, 'SEM-EVENT-INTRUDER-MOVEMENT-001','SEM-FIRE-SPREAD-001','SEM-INFECTION-PROCEDURE-001','SEM-ECLOSION-PROCEDURE-001']},
        {'system':'Intruder Help dispatcher','ruleIds':sorted(item['ruleId'] for item in records if item['ruleId'].startswith('SEM-IH-'))},
        {'system':'endgame/open alternatives','ruleIds':['SEM-ENDGAME-001']},
        {'system':'objective choice','ruleIds':['SEM-RT-010']},
        {'system':'Intruder Phase','ruleIds':['SEM-RT-008']},
        {'system':'Event Phase and Bag Development','ruleIds':['SEM-RT-009','SEM-EVENT-GENERAL-001','SEM-RT-011']},
        {'system':'Cleanup Phase','ruleIds':['SEM-RT-012']},
        {'system':'Doors and Noise','ruleIds':['SEM-DOOR-001','SEM-NOISE-001','SEM-NOISE-NUMERIC-CORRIDOR-001','SEM-NOISE-MARKER-001','SEM-NOISE-HAZARD-001']},
        {'system':'Intruder Attack, base Attack cards, Secure entry, and Character Health','ruleIds':['SEM-INT-004','SEM-SECURE-ENTRY-001','SEM-INT-006','SEM-CONTAMINATION-GAIN-001',*ATTACK_RULE_IDS]},
        {'system':'Tactical Gear','ruleIds':['SEM-ITM-005','SEM-ACT-TACTICAL-001']},
        {'system':'Autodestruction Procedure','ruleIds':['SEM-AUTODESTRUCTION-001']},
        {'system':'base Robot card/component family','ruleIds':['SEM-ACT-ROBOT-001','SEM-ROBOT-SETUP-001','SEM-ROBOT-REVEAL-001','SEM-ROBOT-MOVEMENT-001','SEM-ROBOT-TACTICAL-GEAR-001','SEM-ROBOT-MALFUNCTION-001','SEM-ROBOT-MALFUNCTION-PLACEMENT-001',*ROBOT_RULE_IDS]},
    ],
    'counts':{'systems':18,'pilotRecords':len(records),'fullBaseSemanticCoverageClaimed':False},
    'notYetCovered':['remaining card corpus outside the closed 20-card Event, 12-card Exploration, 6-card Robot, and 20-occurrence Intruder Attack families','all Objectives/Mission Tasks','all remaining Item/Queen Health/Serious Wound effects','remaining setup, map, procedure, and component lifecycle rules'],
}

write('attack-source-index.json', attack_source_index)
write('robot-source-index.json', robot_source_index)
write('exploration-source-index.json', exploration_source_index)
write('event-source-index.json', event_source_index)
write('source-registry.json', source_registry)
write('semantic-rule.schema.json', semantic_schema)
write('semantic-vocabulary.json', semantic_nodes)
write('room-icon-denotations.json', room_icon_denotations)
write('pilots.json', pilot)
write('review-gates.json', semantic_questions)
write('contradictions.json', contradictions)
write('coverage.json', coverage)
print(json.dumps({'sources':source_registry['counts'],'semanticNodes':semantic_nodes['counts'],'pilots':pilot['counts'],'questions':semantic_questions['counts'],'contradictions':contradictions['counts'],'coverage':coverage['counts']},indent=2))
