#!/usr/bin/env python3
"""Generate original, production-safe vector art for the static web game.

The outputs intentionally use only geometric primitives and project game data.
They do not embed or trace collected publisher/community reference images.
"""
from pathlib import Path
import html

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "generated"

ROOMS = {
    "landingZone": ("A", "LANDING", "landing"),
    "drillingRoom": ("A", "DRILL", "industrial"),
    "lifeSupportControlA": ("A", "LIFE A", "systems"),
    "hibernatorium": ("B", "HIBERNATION", "medical"),
    "coolingSystem": ("B", "COOLING", "pipes"),
    "lifeSupportControlB": ("B", "LIFE B", "systems"),
    "serverRoom": ("B", "SERVER", "systems"),
    "lifeSupportControlC": ("C", "LIFE C", "systems"),
    "nest": ("C", "NEST", "organic"),
    "reactor": ("C", "REACTOR", "reactor"),
    "escapeShuttle": ("C", "SHUTTLE", "landing"),
    "armory": ("?", "ARMORY", "industrial"),
    "surgeryRoom": ("?", "SURGERY", "medical"),
    "laboratory": ("?", "LAB", "medical"),
    "gunneryRoom": ("?", "GUNNERY", "industrial"),
    "shelter": ("?", "SHELTER", "secure"),
    "technicalCorridorEntrance": ("?", "TECH ACCESS", "pipes"),
    "sprinklersControl": ("?", "SPRINKLERS", "pipes"),
    "engineRoom": ("?", "ENGINE", "industrial"),
    "storageRoom": ("?", "STORAGE", "secure"),
    "commsRoom": ("?", "COMMS", "systems"),
    "wasteDisposal": ("?", "WASTE", "organic"),
    "airlock": ("?", "AIRLOCK", "secure"),
    "powerGenerator": ("?", "GENERATOR", "reactor"),
}

CHARACTERS = {
    "contractor": ("CTR", "#d89248", "versatile"),
    "recon": ("RCN", "#54b9b0", "recon"),
    "officer": ("OFF", "#cf6a76", "command"),
    "medicalSupport": ("MED", "#73bd8a", "medical"),
    "heavyGunOperator": ("HGO", "#b49ad7", "heavy"),
    "combatEngineer": ("ENG", "#d6b95d", "engineer"),
}

INTRUDERS = {
    "larva": ("LARVA", "#99c45a"),
    "drone": ("DRONE", "#cf8245"),
    "adult": ("ADULT", "#cc4e56"),
    "queen": ("QUEEN", "#d65ac8"),
}


def write(rel: str, text: str) -> None:
    path = OUT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def doc(body: str, viewbox="0 0 256 256") -> str:
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}" role="img">
<!-- Original geometric game art generated by scripts/generate_game_art.py; no source imagery embedded. -->
{body}
</svg>
'''


def room_motif(kind: str) -> str:
    motifs = {
        "landing": '''<circle cx="128" cy="126" r="56"/><circle cx="128" cy="126" r="30"/><path d="M128 52v36M128 164v36M54 126h36M166 126h36"/><path d="m115 126 13-13 13 13-13 13z"/>''',
        "industrial": '''<path d="M54 85h148M54 171h148M72 56v144M184 56v144"/><circle cx="128" cy="128" r="32"/><path d="M128 83v90M83 128h90M96 96l64 64M160 96l-64 64"/>''',
        "systems": '''<rect x="61" y="66" width="134" height="114" rx="8"/><path d="M77 85h102M77 105h48M77 125h102M77 145h66"/><circle cx="166" cy="105" r="10"/><path d="M88 180v20M128 180v20M168 180v20"/>''',
        "medical": '''<circle cx="128" cy="128" r="62"/><path d="M113 82h30v31h31v30h-31v31h-30v-31H82v-30h31z"/><path d="M66 66l28 28M190 66l-28 28M66 190l28-28M190 190l-28-28"/>''',
        "pipes": '''<path d="M52 82h64q16 0 16 16v60q0 16 16 16h56M52 174h35q16 0 16-16v-34q0-16 16-16h85"/><circle cx="132" cy="128" r="18"/><path d="M132 110v36M114 128h36"/>''',
        "organic": '''<path d="M53 159q34-72 75-29 39-51 76 21M61 184q38-49 67-14 31-43 68 5"/><circle cx="91" cy="115" r="17"/><circle cx="151" cy="92" r="23"/><circle cx="171" cy="143" r="13"/><path d="M128 44v44M100 52l19 37M156 52l-19 37"/>''',
        "reactor": '''<circle cx="128" cy="128" r="69"/><circle cx="128" cy="128" r="44"/><circle cx="128" cy="128" r="15"/><path d="M128 43v42M128 171v42M43 128h42M171 128h42M68 68l30 30M188 68l-30 30M68 188l30-30M188 188l-30-30"/>''',
        "secure": '''<rect x="58" y="62" width="140" height="132" rx="12"/><path d="M80 84h96v88H80zM104 84V66h48v18M104 172v20M152 172v20"/><circle cx="128" cy="128" r="17"/><path d="M128 128v24"/>''',
    }
    return motifs[kind]


def room_svg(room_id: str, section: str, label: str, kind: str) -> str:
    palettes = {
        "A": ("#122a25", "#3c7d6d", "#78c4ae"),
        "B": ("#142632", "#3e7191", "#7db6d0"),
        "C": ("#2b1a22", "#8d4a5b", "#d48a98"),
        "?": ("#20272b", "#566b72", "#9db3b9"),
    }
    bg, edge, ink = palettes[section]
    motif = room_motif(kind)
    safe = html.escape(label)
    return doc(f'''<defs>
<radialGradient id="g"><stop stop-color="{edge}" stop-opacity=".34"/><stop offset="1" stop-color="{bg}" stop-opacity=".96"/></radialGradient>
<pattern id="grid" width="18" height="18" patternUnits="userSpaceOnUse"><path d="M18 0H0V18" fill="none" stroke="{ink}" stroke-opacity=".08"/></pattern>
</defs>
<path d="M128 5l123 59v128l-123 59L5 192V64z" fill="url(#g)" stroke="{edge}" stroke-width="8"/>
<path d="M128 13l115 56v118l-115 56L13 187V69z" fill="url(#grid)"/>
<g fill="none" stroke="{ink}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" opacity=".42">{motif}</g>
<path d="M35 211h186" stroke="{edge}" stroke-width="22" opacity=".78"/>
<text x="128" y="218" fill="#e8f0f2" font-family="system-ui,sans-serif" font-size="16" font-weight="700" text-anchor="middle" letter-spacing="2">{safe}</text>''')


def character_svg(char_id: str, code: str, color: str, kind: str) -> str:
    extras = {
        "versatile": '<path d="M38 79h20M70 79h20M64 57v20"/>',
        "recon": '<path d="M36 83l28-20 28 20M64 63V42"/>',
        "command": '<path d="M41 77h46M48 67h32M57 57h14"/>',
        "medical": '<path d="M55 51h18v17h17v18H73v17H55V86H38V68h17z"/>',
        "heavy": '<path d="M31 82h66M38 67h52M45 52h38"/>',
        "engineer": '<path d="M42 91l44-44M42 47l44 44M64 41v57"/>',
    }[kind]
    return doc(f'''<defs><radialGradient id="g"><stop stop-color="{color}" stop-opacity=".55"/><stop offset="1" stop-color="#0a1015"/></radialGradient></defs>
<circle cx="64" cy="64" r="60" fill="#071015" stroke="{color}" stroke-width="5"/>
<circle cx="64" cy="64" r="51" fill="url(#g)" stroke="#dce8eb" stroke-opacity=".34"/>
<path d="M21 98q8-35 31-39V39q0-12 12-12t12 12v20q23 4 31 39" fill="#101a20" stroke="{color}" stroke-width="5"/>
<path d="M48 45q16-13 32 0v18H48z" fill="#29363d" stroke="#dce8eb" stroke-opacity=".5"/>
<g fill="none" stroke="{color}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round">{extras}</g>
<rect x="31" y="101" width="66" height="21" rx="10" fill="#081015" stroke="{color}" stroke-width="2"/>
<text x="64" y="116" fill="#f1f5f6" font-family="system-ui,sans-serif" font-size="13" font-weight="800" text-anchor="middle" letter-spacing="2">{html.escape(code)}</text>''', "0 0 128 128")


def intruder_svg(kind: str, label: str, color: str) -> str:
    shapes = {
        "larva": '<path d="M24 75q9-42 40-42t40 42q-5 27-40 29T24 75z"/><path d="M42 49L25 31M86 49l17-18M43 83l-23 16M85 83l23 16"/>',
        "drone": '<path d="M22 76q8-34 30-34l12-23 12 23q22 0 30 34-14 26-42 26S36 102 22 76z"/><path d="M42 49L20 29M86 49l22-20M38 83l-24 12M90 83l24 12"/>',
        "adult": '<path d="M28 89q3-39 23-50L64 13l13 26q20 11 23 50-18 20-36 20T28 89z"/><path d="M43 45L17 21M85 45l26-24M37 73L11 83M91 73l26 10"/><path d="M53 55l11 11 11-11"/>',
        "queen": '<path d="M20 93q4-39 28-51L64 9l16 33q24 12 28 51-19 20-44 20T20 93z"/><path d="M38 47L12 15M90 47l26-32M32 70L6 63M96 70l26-7M41 95l-25 19M87 95l25 19"/><path d="M45 34L26 8M83 34l19-26M48 61l16 17 16-17"/>',
    }[kind]
    return doc(f'''<defs><radialGradient id="g"><stop stop-color="{color}" stop-opacity=".62"/><stop offset="1" stop-color="#100d12"/></radialGradient></defs>
<circle cx="64" cy="64" r="60" fill="#090c10" stroke="{color}" stroke-width="4"/>
<g fill="url(#g)" stroke="{color}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round">{shapes}</g>
<rect x="25" y="102" width="78" height="20" rx="10" fill="#090c10" stroke="{color}" stroke-width="2"/>
<text x="64" y="116" fill="#fff" font-family="system-ui,sans-serif" font-size="12" font-weight="800" text-anchor="middle" letter-spacing="1">{label}</text>''', "0 0 128 128")


def card_back(name: str, color: str, icon: str) -> str:
    return doc(f'''<defs><pattern id="p" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M0 10h20M10 0v20" stroke="{color}" stroke-opacity=".08"/></pattern><radialGradient id="g"><stop stop-color="{color}" stop-opacity=".28"/><stop offset="1" stop-color="#10171d"/></radialGradient></defs>
<rect x="5" y="5" width="246" height="346" rx="15" fill="url(#g)" stroke="{color}" stroke-width="7"/>
<rect x="16" y="16" width="224" height="324" rx="10" fill="url(#p)" stroke="{color}" stroke-opacity=".4"/>
<circle cx="128" cy="165" r="66" fill="#0b1217" stroke="{color}" stroke-width="4"/>
<text x="128" y="180" fill="{color}" font-family="system-ui,sans-serif" font-size="58" font-weight="900" text-anchor="middle">{icon}</text>
<text x="128" y="304" fill="#e5edef" font-family="system-ui,sans-serif" font-size="18" font-weight="800" text-anchor="middle" letter-spacing="3">{html.escape(name)}</text>''', "0 0 256 356")


def board_svg() -> str:
    return doc('''<defs>
<radialGradient id="bg"><stop stop-color="#172932"/><stop offset=".56" stop-color="#0c151b"/><stop offset="1" stop-color="#05090c"/></radialGradient>
<pattern id="deck" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M0 24h48M24 0v48" stroke="#6e9cac" stroke-opacity=".045"/><circle cx="24" cy="24" r="2" fill="#89bac8" fill-opacity=".1"/></pattern>
<linearGradient id="rail" x2="0" y2="1"><stop stop-color="#243d47"/><stop offset=".5" stop-color="#0a1116"/><stop offset="1" stop-color="#1e343d"/></linearGradient>
</defs>
<rect width="1200" height="900" fill="url(#bg)"/>
<rect width="1200" height="900" fill="url(#deck)"/>
<path d="M16 16h1168v868H16z" fill="none" stroke="url(#rail)" stroke-width="24"/>
<path d="M38 40h1124M38 820h1124" stroke="#78bfd0" stroke-opacity=".18" stroke-width="2" stroke-dasharray="18 12"/>
<g fill="#83b8c5" fill-opacity=".16"><path d="M55 34h170l-18 13H73z"/><path d="M975 34h170l-18 13H993z"/><path d="M55 853h170l-18 13H73z"/><path d="M975 853h170l-18 13H993z"/></g>
<text x="600" y="32" fill="#9bc6cf" fill-opacity=".28" font-family="system-ui,sans-serif" font-size="13" font-weight="700" text-anchor="middle" letter-spacing="8">FACILITY TACTICAL DISPLAY</text>''', "0 0 1200 900")


def symbol(symbol_id: str, body: str) -> str:
    return f'<symbol id="i-{symbol_id}" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">{body}</g></symbol>'


def symbols_svg() -> str:
    symbols = {
        "move": '<path d="M4 20L20 4M10 4h10v10"/>',
        "cautious": '<path d="M3 20L17 6M9 6h8v8M20 15v6M17 18h6"/>',
        "shoot": '<circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="2"/><path d="M12 2v4M12 18v4M2 12h4M18 12h4"/>',
        "burst": '<path d="M12 2l2.5 6 6.5-2-3 6 4 5-7-.5L12 22l-3-5.5-7 .5 4-5-3-6 6.5 2z"/>',
        "melee": '<path d="M5 21l4-4M7 3l14 14-4 4L3 7zM14 6l3-3 4 4-3 3"/>',
        "item": '<path d="M4 8h16v12H4zM8 8V4h8v4M8 12h8"/>',
        "gear": '<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/>',
        "room": '<path d="M7 2h10l5 5v10l-5 5H7l-5-5V7zM8 8h8v8H8z"/>',
        "search": '<circle cx="10" cy="10" r="6"/><path d="M15 15l6 6"/>',
        "trade": '<path d="M3 7h16M15 3l4 4-4 4M21 17H5M9 13l-4 4 4 4"/>',
        "robot": '<rect x="4" y="6" width="16" height="14" rx="3"/><path d="M12 2v4M8 12h.1M16 12h.1M8 17h8"/>',
        "pass": '<path d="M4 4l8 8-8 8M12 4l8 8-8 8"/>',
        "sprint": '<circle cx="14" cy="4" r="2"/><path d="M10 9l4-3 3 4 3 1M14 10l-3 5-6 2M11 15l4 5"/>',
        "rest": '<path d="M5 5h8L5 13h8M14 10h6l-6 7h6"/>',
        "reinforce": '<path d="M4 20V4h16v16M8 4v16M16 4v16M4 9h16M4 15h16"/>',
        "drill": '<path d="M3 7h12l6 5-6 5H3zM7 7v10M11 7v10"/>',
        "command": '<path d="M3 10h4l9-5v14l-9-5H3zM8 15l2 6M19 9q3 3 0 6"/>',
        "health": '<path d="M12 21S3 15 3 8q0-5 4-5 3 0 5 3 2-3 5-3 4 0 4 5 0 7-9 13z"/>',
        "oxygen": '<path d="M12 2q7 8 7 13a7 7 0 1 1-14 0q0-5 7-13z"/><path d="M9 16q1 2 3 2"/>',
        "cards": '<rect x="5" y="3" width="13" height="17" rx="2"/><path d="M9 7h5M9 11h5M9 15h3"/>',
        "contamination": '<circle cx="12" cy="12" r="3"/><path d="M12 9V3M9.5 10.5L4 7M9.5 13.5L4 17M12 15v6M14.5 13.5L20 17M14.5 10.5L20 7"/>',
        "wound": '<path d="M4 4l16 16M15 3l-4 7 4 4-6 7"/>',
        "larva": '<path d="M5 14q2-8 7-8t7 8q-2 5-7 5t-7-5zM8 9L5 5M16 9l3-4"/>',
        "objective": '<path d="M4 3h16v18H4zM8 8h8M8 12h8M8 16h5"/>',
        "computer": '<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4M7 9h10"/>',
        "fire": '<path d="M13 2q3 5 0 8 5-2 6 4a7 7 0 1 1-14 0q0-4 4-7 0 4 3 5 3-4 1-10z"/>',
        "malfunction": '<path d="M13 2L4 14h7l-1 8 10-13h-7z"/>',
        "secure": '<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/>',
        "noise": '<path d="M4 9h4l5-4v14l-5-4H4zM17 8q4 4 0 8M19 5q7 7 0 14"/>',
        "ammo": '<path d="M9 3h6v18H9zM9 7h6M12 3V1"/>',
        "grenade": '<circle cx="12" cy="14" r="7"/><path d="M9 7V3h6v4M15 4l4 2"/>',
        "data": '<path d="M5 3h11l3 3v15H5zM9 8h6M9 12h6M9 16h4"/>',
    }
    return doc('<defs>' + ''.join(symbol(k, v) for k, v in symbols.items()) + '</defs>', "0 0 24 24")


def main() -> None:
    write("board/facility-playmat.svg", board_svg())
    for room_id, (section, label, kind) in ROOMS.items():
        write(f"rooms/{room_id}.svg", room_svg(room_id, section, label, kind))
    for char_id, (code, color, kind) in CHARACTERS.items():
        write(f"characters/{char_id}.svg", character_svg(char_id, code, color, kind))
    for kind, (label, color) in INTRUDERS.items():
        write(f"intruders/{kind}.svg", intruder_svg(kind, label, color))
    for name, color, icon in [
        ("ACTION", "#4c9ac4", "↗"), ("CONTAMINATION", "#55b987", "⌬"),
        ("OBJECTIVE", "#c56069", "◎"), ("RED ITEM", "#d65a61", "▰"),
        ("YELLOW ITEM", "#d0ae4f", "◆"), ("GREEN ITEM", "#5bab7a", "+"),
    ]:
        slug = name.lower().replace(" ", "-")
        write(f"cards/{slug}.svg", card_back(name, color, icon))
    write("ui-symbols.svg", symbols_svg())
    print(f"Generated {1 + len(ROOMS) + len(CHARACTERS) + len(INTRUDERS) + 6 + 1} SVG assets in {OUT}")


if __name__ == "__main__":
    main()
