from __future__ import annotations


def build_general_records(record, assertion, timing, participant, condition, decision, operation, event_rule_ids):
    records=[]

    records.append(record(
        'SEM-RT-010','Choosing an Objective','source-backed','procedure','official-primary','verbatim-structure',
        [assertion('SA-RT010-1','SRC-RULEBOOK','printed pages 13 and 39 / Choosing an Objective',['timing','decisions','informationPolicy','operations','outcomes'],'Once per game during their Turn, before or after an Action, a player removes one Objective unseen, keeps the other, advances the Objective Choice track, and draws the track reward.','docs/rules/01-round-and-turns.md:RT-010')],
        ['term.objective','term.objective-card','term.private-objective','term.mission-objective','icon.actionCard'],['tax.entity.information.objective','tax.entity.component.card.objective','tax.entity.information.objective.private','tax.entity.information.objective.mission'],[],
        timing('TW-OBJECTIVE-CHOICE','tax.process.temporal.turn','during','once-per-player-per-game'),[participant('P-CHOOSING-PLAYER','actor','tax.entity.agent.player'),participant('P-CHARACTER','controlled-actor','tax.entity.agent.character')],'may',
        [condition('C-OBJ-WINDOW','all',[{'predicate':'Player has not previously chosen an Objective'},{'predicate':'current timing is before or after a Turn Action, not during one'}],['SA-RT010-1'])],
        [decision('D-OBJECTIVE','P-CHOOSING-PLAYER','player-choice',1,1,False,'owner-private',['the Player’s two Objective cards'])],
        [{'informationId':'I-OBJECTIVE-PAIR','subjectRef':'both Objective identities and removed choice','audience':'owner-private','revealTrigger':'chosen Objective at End of Game only','secrecy':'removed Objective is not shown; kept Objective remains hidden'},{'informationId':'I-OBJECTIVE-TRACK','subjectRef':'track position and cards drawn','audience':'public','revealTrigger':'choice resolution','secrecy':'none'}],[],[],
        [operation('S01',1,'choose','may','P-CHOOSING-PLAYER','one Objective to remove',['SA-RT010-1'],decision_ref='D-OBJECTIVE'),operation('S02',2,'transition-zone','must','P-CHOOSING-PLAYER','unchosen/removed Objective',['SA-RT010-1'],transition={'from':'tax.scaffold.zone.hand','to':'tax.scaffold.zone.removed-from-game'}),operation('S03',3,'set-state','must','P-CHOOSING-PLAYER','other Objective retained as chosen',['SA-RT010-1']),operation('S04',4,'change-value','if-able','rules-system','Objective Choice track',['SA-RT010-1'],value_change={'amount':-1,'value':'one track position'}),operation('S05',5,'draw-random','must','P-CHOOSING-PLAYER','Action cards according to pre-move track position: 3/2/2/1',['SA-RT010-1'])],
        {'policy':'all-or-nothing-selection','unit':'Objective choice procedure','onImpossible':'may be initiated only in its legal window'}, {'kind':'persistent-until-endgame'}, {'policy':'once per Player per game'}, [{'condition':'chosen Objective not fulfilled at endgame','result':'Character cannot win'}], [], []))

    records.append(record(
        'SEM-RT-008','Intruder Phase','source-backed','sequence','official-primary','verbatim-structure',
        [assertion('SA-RT008-1','SRC-RULEBOOK','printed pages 14–15 / Intruder Phase',['timing','operations','targets','partialResolution'],'Resolve Intruders Burning, then Intruder Attacks, with Rooms top-left row order and larger Intruders first.','docs/rules/01-round-and-turns.md:RT-008')],
        ['term.intruder-phase','icon.fire','term.hit','term.attack','term.turn-order'],['tax.process.temporal.phase.intruder','tax.entity.component.marker.fire','tax.process.operation.hit','tax.process.attack','tax.value.turn-order'],[],
        timing('TW-INTRUDER-PHASE','tax.process.temporal.phase.intruder','during','once-per-round'),[participant('P-RULES','rules-system'),participant('P-INTRUDERS','collection','tax.entity.agent.intruder'),participant('P-CHARACTERS','collection','tax.entity.agent.character')],'must',[],[],[{'informationId':'I-INTRUDER-PHASE','subjectRef':'Intruder locations, Hits, targets, attacks','audience':'public','revealTrigger':'continuous','secrecy':'none'}],[],
        [{'targetId':'T-ATTACKED-CHARACTER','selectorRef':'rules-system','eligibleTaxonIds':['tax.entity.agent.character'],'cardinality':{'min':0,'max':1},'selectionMode':'deterministic-turn-order','visibility':'public'}],
        [operation('S01',1,'change-value','if-able','each Intruder in a Room with Fire','Hits',['SA-RT008-1'],value_change={'amount':1,'valueTaxonId':'tax.process.operation.hit'},repeat={'scope':'each matching Intruder'}),operation('S02',2,'remove-component','if-able','rules-system','1 Egg if Fire is in the Nest',['SA-RT008-1']),operation('S03',3,'invoke-process','if-able','each Intruder in a Room with Character','Intruder Attack',['SA-RT008-1'],target_ref='T-ATTACKED-CHARACTER',repeat={'roomOrder':'top-left row by row','intruderOrder':'Queen > Drone > Adult > Larva','targetOrder':'first in Turn order, then next if target dies/leaves'})],
        {'policy':'ordered-complete','unit':'Intruder Phase step','onImpossible':'finite-component and target availability rules apply per operation'}, {'kind':'phase'}, {'policy':'once per Round'}, [], [], []))

    records.append(record(
        'SEM-RT-009','Event Phase','source-backed','sequence','official-primary','verbatim-structure',
        [assertion('SA-RT009-PHASE','SRC-RULEBOOK','printed pages 12, 14–15 / Event Phase',['timing','operations'],'Event Phase resolves one Event card and then Bag Development.','docs/rules/01-round-and-turns.md:RT-009')],
        ['term.event-phase','term.event-card'],['tax.process.temporal.phase.event','tax.entity.component.card.event'],[],
        timing('TW-EVENT-PHASE','tax.process.temporal.phase.event','during','once-per-round'),[participant('P-RULES','rules-system')],'must',[],[],[{'informationId':'I-EVENT-PHASE','subjectRef':'Event card and Bag Development results','audience':'public','revealTrigger':'resolution','secrecy':'none'}],[],[],
        [operation('S01',1,'invoke-process','must','rules-system','Event card resolution',['SA-RT009-PHASE'],invoke='SEM-EVENT-GENERAL-001'),operation('S02',2,'invoke-process','must','rules-system','Bag Development',['SA-RT009-PHASE'],invoke='SEM-RT-011')],
        {'policy':'ordered-complete','unit':'Event Phase step','onImpossible':'Event-card per-sentence policy belongs to invoked record'}, {'kind':'phase'}, {'policy':'once per Round'}, [], [], []))

    records.append(record(
        'SEM-EVENT-GENERAL-001','Generic Event card resolution','source-backed','event','official-primary','verbatim-structure',
        [assertion('SA-EVENT-GEN','SRC-RULEBOOK','printed page 15 / lines 3269–3299',['operations','partialResolution','timing'],'Draw an Event, resolve movement, main effect, secondary effect, then discard; ignore an impossible sentence and continue.','docs/rules/00-foundations.md:FND-003')],
        ['term.event-card','term.discard','term.turn-order'],['tax.entity.component.card.event','tax.process.operation.discard','tax.value.turn-order'],[],
        timing('TW-EVENT-CARD','tax.process.temporal.phase.event','during-event-card-resolution','once-per-drawn-Event'),[participant('P-RULES','rules-system')],'must',[],[],[{'informationId':'I-EVENT-CARD','subjectRef':'drawn Event and all results','audience':'public','revealTrigger':'draw','secrecy':'none'}],[],[],
        [operation('S01',1,'draw-random','must','rules-system','top Event card into resolution',['SA-EVENT-GEN']),operation('S02',2,'invoke-selected-process','must','rules-system','exact Event-card semantic record selected by source occurrence identity',['SA-EVENT-GEN'],notes='Dispatch uses the locked source occurrence/cardId crosswalk, never display title alone.'),operation('S03',3,'transition-zone','if-able','rules-system','resolved Event card still in resolution',['SA-EVENT-GEN'],conditions=['current Event card was not itself reshuffled by its printed sentence'],transition={'from':'sem.zone.card-in-resolution','to':'tax.scaffold.zone.discard-pile','positionRef':'sem.position.deck-top'})],
        {'policy':'per-sentence-continue','unit':'Event-card sentence','onImpossible':'ignore only that impossible sentence and continue remaining sentences/steps'}, {'kind':'instantaneous-event-resolution'}, {'policy':'not-applicable'}, [], [], []))
    records[-1]['operations'][1]['dispatchRuleIds']=list(event_rule_ids)

    records.append(record(
        'SEM-RT-011','Bag Development','source-backed','procedure','official-primary','verbatim-structure',
        [assertion('SA-BAG-DEV','SRC-RULEBOOK','printed pages 15–16 / Bag Development',['operations','partialResolution'],'Draw one Intruder token, use the front only, resolve the type row, and return/discard according to token lifecycle; Blank returns to bag.','docs/rules/01-round-and-turns.md:RT-011')],
        ['term.queen','term.drone','term.adult','term.larva'],['tax.entity.agent.intruder.queen','tax.entity.agent.intruder.drone','tax.entity.agent.intruder.adult','tax.entity.agent.intruder.larva','tax.scaffold.zone.intruder-bag','tax.scaffold.zone.token-pile'],[],
        timing('TW-BAG-DEV','tax.process.temporal.phase.event','during','once-per-Event-Phase'),[participant('P-RULES','rules-system')],'must',[],[],[{'informationId':'I-BAG-TOKEN','subjectRef':'drawn token front and result','audience':'public','revealTrigger':'draw','secrecy':'back ignored for this procedure'}],[],[],
        [operation('S01',1,'draw-random','must','rules-system','1 Intruder token from bag',['SA-BAG-DEV']),operation('S02',2,'branch','must','rules-system','token-front type and current Queen side',['SA-BAG-DEV']),operation('S03',3,'invoke-process','if-able','rules-system','Queen-alive Queen row',['SA-BAG-DEV'],conditions=['drawn token is Queen','Help Sheet is Queen Alive'],invoke='SEM-IH-QA-B-01'),operation('S04',4,'invoke-process','if-able','rules-system','Queen-dead Queen row',['SA-BAG-DEV'],conditions=['drawn token is Queen','Help Sheet is Queen Dead'],invoke='SEM-IH-QD-B-01'),operation('S05',5,'invoke-process','if-able','rules-system','Queen-alive Adult/Drone row',['SA-BAG-DEV'],conditions=['drawn token is Adult or Drone','Help Sheet is Queen Alive'],invoke='SEM-IH-QA-B-02'),operation('S06',6,'invoke-process','if-able','rules-system','Queen-dead Adult/Drone row',['SA-BAG-DEV'],conditions=['drawn token is Adult or Drone','Help Sheet is Queen Dead'],invoke='SEM-IH-QD-B-02'),operation('S07',7,'invoke-process','if-able','rules-system','Queen-alive Larva row',['SA-BAG-DEV'],conditions=['drawn token is Larva','Help Sheet is Queen Alive'],invoke='SEM-IH-QA-B-03'),operation('S08',8,'invoke-process','if-able','rules-system','Queen-dead Larva row',['SA-BAG-DEV'],conditions=['drawn token is Larva','Help Sheet is Queen Dead'],invoke='SEM-IH-QD-B-03'),operation('S09',9,'invoke-process','if-able','rules-system','Queen-alive Blank row',['SA-BAG-DEV'],conditions=['drawn token is Blank','Help Sheet is Queen Alive'],invoke='SEM-IH-QA-BOTTOM-01'),operation('S10',10,'invoke-process','if-able','rules-system','Queen-dead Blank row',['SA-BAG-DEV'],conditions=['drawn token is Blank','Help Sheet is Queen Dead'],invoke='SEM-IH-QD-BOTTOM-01')],
        {'policy':'source-limited-components','unit':'requested token','onImpossible':'place/add as many requested components as available; ignore excess'}, {'kind':'instantaneous-procedure'}, {'policy':'once per Event Phase'}, [], [], []))

    records.append(record(
        'SEM-RT-012','Cleanup Phase','source-backed-with-open-question','sequence','official-primary','open-alternatives',
        [assertion('SA-CLEANUP','SRC-RULEBOOK','printed pages 15–16 / Cleanup Phase',['operations','unresolvedQuestionRefs'],'Pass Starting Player clockwise, refill each hand to 5 with reshuffle as needed, then advance Round marker and resolve entered token.','docs/rules/01-round-and-turns.md:RT-012')],
        ['term.cleanup-phase','term.starting-player','term.round-marker','icon.actionCard'],['tax.process.temporal.phase.cleanup','tax.role.starting-player','tax.entity.component.token.round','tax.entity.component.card.action'],[],
        timing('TW-CLEANUP','tax.process.temporal.phase.cleanup','during','once-per-round'),[participant('P-RULES','rules-system'),participant('P-PLAYERS','collection','tax.entity.agent.player')],'must',[],[],[{'informationId':'I-CLEANUP','subjectRef':'Starting Player, hand counts, Round track/token effects','audience':'public-except-card-identities','revealTrigger':'resolution','secrecy':'drawn Action/Contamination identities remain owner-private'}],[],[],
        [operation('S01',1,'resolve-open-alternative','must','rules-system','OQ-003 Starting Player transfer',['SA-CLEANUP']),operation('S02',2,'draw-random','must','each eligible Player','Action cards until hand size is 5',['SA-CLEANUP'],repeat={'ifDeckEmpties':'shuffle discard pile into Action deck and continue'}),operation('S03',3,'change-value','if-able','rules-system','Round marker +1',['SA-CLEANUP'],value_change={'amount':1,'value':'Round track position'}),operation('S04',4,'invoke-process','if-able','rules-system','token effect on newly entered Round space',['SA-CLEANUP']),operation('S05',5,'invoke-process','must','rules-system','End of the Game',['SA-CLEANUP'],conditions=['Round marker was already on final space'],invoke='SEM-ENDGAME-001')],
        {'policy':'ordered-complete','unit':'Cleanup step','onImpossible':'OQ-003 remains open; finite deck reshuffle is explicit'}, {'kind':'phase'}, {'policy':'once per Round'}, [], ['OQ-003'], []))

    records.append(record(
        'SEM-DOOR-001','Door states, adjacency, and blocking','source-backed','constraint','official-errata','source-composed',
        [assertion('SA-DOOR-RB','SRC-RULEBOOK','printed pages 22–23 / Doors',['operations','preconditions'],'Door states are Open, Closed, Destroyed; Destroyed behaves Open and cannot close; Closed blocks path/effects but not adjacency.','docs/rules/02-character-actions.md:Doors'),assertion('SA-DOOR-FAQ','SRC-FAQ','General rules #8',['operations','partialResolution'],'Closed Doors block effects/objects except Noise marker placement/discard.','docs/rules/02-character-actions.md:Doors')],
        ['term.door','term.opened','term.closed','term.destroyed'],['tax.entity.spatial.door','tax.state.opened','tax.state.closed','tax.state.destroyed'],[],
        timing('TW-DOOR','tax.state.door','when-triggered','per-Door-state/effect-check'),[participant('P-RULES','rules-system')],'must',[],[],[{'informationId':'I-DOOR','subjectRef':'Door state and blocked path','audience':'public','revealTrigger':'continuous','secrecy':'none'}],[],[],
        [operation('S01',1,'set-state','if-able','Door','tax.state.opened',['SA-DOOR-RB'],conditions=['appropriate effect opens Door']),operation('S02',2,'set-state','if-able','Door','tax.state.closed',['SA-DOOR-RB'],conditions=['appropriate effect closes Door','Door has a Door slot','Door is not Destroyed']),operation('S03',3,'set-state','if-able','Door','tax.state.destroyed',['SA-DOOR-RB'],conditions=['appropriate effect destroys Door']),operation('S04',4,'evaluate-condition','must','rules-system','Closed Door blocks movement/effects but preserves adjacency',['SA-DOOR-RB','SA-DOOR-FAQ']),operation('S05',5,'evaluate-condition','must','rules-system','Noise markers may still be placed/discarded through Closed Door',['SA-DOOR-FAQ'])],
        {'policy':'per-effect-check','unit':'attempted path/effect','onImpossible':'blocked effect does not cross; source-specific enclosing resolution applies'}, {'kind':'persistent-state-constraint'}, {'policy':'one state per Door; Destroyed is irreversible'}, [], [], []))

    records.append(record(
        'SEM-NOISE-001','Noise Roll','source-backed','procedure','official-primary','verbatim-structure',
        [assertion('SA-NOISE','SRC-RULEBOOK','printed page 25 / lines 4669–4705',['operations','partialResolution'],'Roll Noise die; resolve every adjacent matching-value Corridor in order or resolve Hazard using token front; no matching Corridor means nothing.','docs/rules/02-character-actions.md:Noise')],
        ['term.noise-roll','icon.noise','icon.intruder','term.corridor'],['tax.process.sequence.noise-roll','tax.entity.component.marker.noise','tax.entity.agent.intruder','tax.entity.spatial.corridor'],[],
        timing('TW-NOISE','tax.process.sequence.noise-roll','when-triggered','per-required-Noise-roll'),[participant('P-ROLLER','actor','tax.entity.agent.character'),participant('P-RULES','rules-system')],'must',[],[],[{'informationId':'I-NOISE','subjectRef':'die result, affected Corridors, token/result','audience':'public','revealTrigger':'roll/draw','secrecy':'none'}],[],[],
        [operation('S01',1,'draw-random','must','P-ROLLER','Noise die result',['SA-NOISE']),operation('S02',2,'branch','must','P-RULES','numeric or Hazard result',['SA-NOISE']),operation('S03',3,'invoke-process','if-able','P-RULES','per-matching-Corridor Intruder move and immediate Attack',['SA-NOISE'],conditions=['numeric result','matching Corridor contains Intruder'],invoke='SEM-NOISE-NUMERIC-CORRIDOR-001',repeat={'scope':'each matching adjacent Corridor in source order; complete move and Attack before next Corridor'}),operation('S04',4,'invoke-process','if-able','P-RULES','one existing Noise marker',['SA-NOISE'],conditions=['numeric result','matching Corridor contains no Intruder and has Noise marker'],invoke='SEM-NOISE-MARKER-001',repeat={'scope':'every matching adjacent Corridor'}),operation('S05',5,'place-component','if-able','P-RULES','Noise marker',['SA-NOISE'],conditions=['numeric result','matching Corridor contains no Intruder and no Noise marker'],repeat={'scope':'every matching adjacent Corridor'}),operation('S06',6,'invoke-process','if-able','P-RULES','direct Hazard result',['SA-NOISE'],conditions=['Hazard result'],invoke='SEM-NOISE-HAZARD-001')],
        {'policy':'source-conditional-steps','unit':'matching Corridor/result branch','onImpossible':'if no matching numeric Corridor, nothing happens; finite components place as available'}, {'kind':'instantaneous-procedure'}, {'policy':'one die result per roll'}, [], [], []))

    records.append(record(
        'SEM-NOISE-NUMERIC-CORRIDOR-001','Numeric Noise result for one matching Corridor','source-backed','procedure','official-primary','verbatim-structure',
        [assertion('SA-NOISE-CORRIDOR','SRC-RULEBOOK','printed page 25 / numeric Noise result and Surprise Attacks',['preconditions','operations','partialResolution'],'For one matching Corridor containing an Intruder, move its largest Intruder into the rolling Character’s Room and immediately resolve that Intruder’s Attack before resolving the next Corridor.','docs/rules/02-character-actions.md:Noise')],
        ['term.noise-roll','term.corridor','icon.intruder','term.attack'],['tax.process.sequence.noise-roll','tax.entity.spatial.corridor','tax.entity.agent.intruder','tax.process.attack'],[],
        timing('TW-NOISE-CORRIDOR','tax.process.sequence.noise-roll','when-triggered','per-matching-Corridor-with-Intruder'),[participant('P-ROLLER','affected','tax.entity.agent.character'),participant('P-RULES','rules-system')],'must',
        [condition('C-NOISE-CORRIDOR','all',[{'predicate':'numeric Noise result matches this adjacent Corridor'},{'predicate':'Corridor contains at least one Intruder'}],['SA-NOISE-CORRIDOR'])],[],[{'informationId':'I-NOISE-CORRIDOR','subjectRef':'selected largest Intruder, move, and immediate Attack','audience':'public','revealTrigger':'resolution','secrecy':'none'}],[],[],
        [operation('S01',1,'move-entity','must','largest Intruder in this matching Corridor','rolling Character Room',['SA-NOISE-CORRIDOR']),operation('S02',2,'invoke-process','must','moved Intruder','Secure-entry/Attack resolution before next Corridor',['SA-NOISE-CORRIDOR'],invoke='SEM-SECURE-ENTRY-001')],
        {'policy':'ordered-complete','unit':'one matching Corridor','onImpossible':'complete the move and resulting immediate Attack before the next matching Corridor'}, {'kind':'instantaneous-subprocedure'}, {'policy':'once per matching Corridor per numeric Noise result'}, [], [], []))

    records.append(record(
        'SEM-INT-004','Intruder Attack','source-backed','procedure','official-primary','source-composed',
        [assertion('SA-ATTACK','SRC-RULEBOOK','printed pages 15, 25, 32, 34 / Intruder Attacks',['targets','operations','partialResolution'],'Select target by source trigger/Turn order, draw Intruder Attack card, resolve type effect, discard; Larva uses its special procedure.','docs/rules/03-intruders-and-survival.md:INT-004')],
        ['term.attack','term.intruder-attack-card','term.turn-order','term.larva','term.contamination-card'],['tax.process.attack','tax.entity.component.card.intruder-attack','tax.value.turn-order','tax.entity.agent.intruder.larva','tax.entity.component.card.contamination'],[],
        timing('TW-INTRUDER-ATTACK','tax.process.attack','when-triggered','per-attacking-Intruder'),[participant('P-INTRUDER','actor','tax.entity.agent.intruder'),participant('P-TARGET','affected','tax.entity.agent.character'),participant('P-RULES','rules-system')],'must',[],[],[{'informationId':'I-ATTACK','subjectRef':'attacker, target, drawn card, outcome','audience':'public','revealTrigger':'attack/draw','secrecy':'none'}],[],
        [{'targetId':'T-ATTACK','selectorRef':'rules-system','eligibleTaxonIds':['tax.entity.agent.character'],'cardinality':{'min':0,'max':1},'selectionMode':'deterministic-turn-order','visibility':'public'}],
        [operation('S01',1,'select-target','if-able','P-RULES','eligible Character according to trigger/Turn order',['SA-ATTACK'],target_ref='T-ATTACK'),operation('S02',2,'branch','must','P-RULES','Larva or standard Attack',['SA-ATTACK']),operation('S03',3,'draw-random','must','P-RULES','Intruder Attack card',['SA-ATTACK'],conditions=['attacker is not Larva']),operation('S04',4,'invoke-process','must','P-INTRUDER','card effect assigned to attacker type',['SA-ATTACK'],conditions=['attacker is not Larva']),operation('S05',5,'transition-zone','must','P-RULES','resolved Intruder Attack card',['SA-ATTACK'],conditions=['attacker is not Larva'],transition={'from':'sem.zone.card-in-resolution','to':'tax.scaffold.zone.discard-pile','positionRef':'sem.position.deck-top'}),operation('S06',6,'place-component','must','P-RULES','1 Contamination into target discard pile',['SA-ATTACK'],conditions=['attacker is Larva']),operation('S07',7,'move-entity','if-able','Larva','target Character board',['SA-ATTACK'],conditions=['attacker is Larva','target board has no Larva']),operation('S08',8,'remove-component','if-able','P-RULES','attacking Larva',['SA-ATTACK'],conditions=['attacker is Larva','target board already has Larva'])],
        {'policy':'source-conditional-steps','unit':'Attack branch','onImpossible':'no eligible Character means no standard target; prevention/replacement effects are separate semantic records'}, {'kind':'instantaneous-attack'}, {'policy':'one resolution per attacking Intruder'}, [], [], []))

    records.append(record(
        'SEM-INT-006','Character Health, Serious Wounds, and death','source-backed','procedure','official-primary','source-composed',
        [assertion('SA-HEALTH','SRC-RULEBOOK','printed page 18 / Health, Serious Wounds, Death',['operations','decisions','outcomes','duration','stacking'],'Move Health marker, discard crossed Armor, die at Skull; place Serious Wound leftmost, shift Health when occupied section, duplicates do not stack, owner chooses discarded Wound.','docs/rules/03-intruders-and-survival.md:INT-006')],
        ['term.character-health','term.health-point','term.serious-wound-card','term.healthy','term.injured','term.heavily-injured'],['tax.state.health','tax.state.health.point','tax.entity.component.card.serious-wound','tax.state.health.healthy','tax.state.health.injured','tax.state.health.heavily-injured'],[],
        timing('TW-HEALTH','tax.state.health','when-triggered','per-health/wound-effect'),[participant('P-CHARACTER','affected','tax.entity.agent.character'),participant('P-OWNER','decision-owner','tax.entity.agent.player'),participant('P-RULES','rules-system')],'must',[],
        [decision('D-DISCARD-WOUND','P-OWNER','player-choice',1,1,False,'owner-private-until-declaration',['owned Serious Wound copies when an effect discards one'])],
        [{'informationId':'I-HEALTH','subjectRef':'Health marker, Armor, Wounds, death','audience':'public','revealTrigger':'continuous/resolution','secrecy':'none'}],[],[],
        [operation('S01',1,'change-value','must','P-RULES','Health marker right by instructed amount',['SA-HEALTH'],value_change={'amount':'source-instructed','value':'Health track position'}),operation('S02',2,'remove-component','if-able','P-RULES','Armor crossed by Health marker',['SA-HEALTH']),operation('S03',3,'set-state','if-able','P-CHARACTER','sem.state.participation.dead',['SA-HEALTH'],conditions=['Health marker reaches Skull']),operation('S04',4,'draw-random','if-able','P-RULES','Serious Wound card',['SA-HEALTH'],conditions=['effect grants Serious Wound']),operation('S05',5,'place-component','must','P-RULES','drawn Wound in leftmost empty Health section',['SA-HEALTH']),operation('S06',6,'change-value','if-able','P-RULES','Health marker to first empty slot of next section',['SA-HEALTH'],conditions=['Health marker occupied the Wound section'],value_change={'amount':'advance-to-first-empty-slot','value':'Health track position'}),operation('S07',7,'choose','if-able','P-OWNER','which duplicate/copy Wound to discard',['SA-HEALTH'],decision_ref='D-DISCARD-WOUND'),operation('S08',8,'remove-component','if-able','P-RULES','selected Wound',['SA-HEALTH'],decision_ref='D-DISCARD-WOUND'),operation('S09',9,'set-state','must','P-RULES','remaining Wounds slide left; Health marker does not move',['SA-HEALTH']),operation('S10',10,'remove-component','must','P-RULES','all Items carried by Character',['SA-HEALTH'],conditions=['Character dies'])],
        {'policy':'ordered-complete','unit':'health/wound effect','onImpossible':'restore may restore fewer points; finite Wound deck/component rules apply'}, {'kind':'persistent-until-healed/discarded/death'}, {'policy':'duplicate Wound cards may coexist but printed effects do not stack'}, [{'condition':'Health marker reaches Skull','result':'Character dies, loses carried Items, no longer participates'}], [], []))

    records.append(record(
        'SEM-ITM-005','Tactical Gear tokens and slots','source-backed','constraint','official-primary','verbatim-structure',
        [assertion('SA-GEAR','SRC-RULEBOOK','printed pages 16 and 29 / Tactical Gear',['preconditions','operations','partialResolution'],'Gained tokens occupy empty matching/Any slots; one token per slot; tokens are limited; losing Item loses its tokens.','docs/rules/04-items-and-equipment.md:ITM-005')],
        ['term.tactical-gear-token','term.tactical-gear-slot','term.tactical-belt','icon.ammoToken','icon.grenadeToken','icon.oxygenToken','icon.medpackToken'],['tax.entity.component.token.tactical-gear','tax.entity.component.slot.tactical-gear','tax.entity.component.storage.tactical-belt','tax.scaffold.supply-pool'],[],
        timing('TW-GEAR','tax.entity.component.token.tactical-gear','when-triggered','per-gain/use/loss'),[participant('P-OWNER','decision-owner','tax.entity.agent.player'),participant('P-CHARACTER','actor','tax.entity.agent.character'),participant('P-RULES','rules-system')],'must',
        [condition('C-GEAR-SLOT','all',[{'predicate':'chosen slot is empty'},{'predicate':'slot type matches token or is Any'}],['SA-GEAR'])],
        [decision('D-GEAR-SLOT','P-OWNER','player-choice',1,1,False,'public-on-placement',['compatible empty Tactical Gear slots'])],
        [{'informationId':'I-GEAR','subjectRef':'token type, side, slot, supply availability','audience':'public','revealTrigger':'continuous/placement','secrecy':'none'}],[],
        [{'targetId':'T-GEAR-SLOT','selectorRef':'P-OWNER','eligibleTaxonIds':['tax.entity.component.slot.tactical-gear'],'cardinality':{'min':1,'max':1},'selectionMode':'player-choice','visibility':'public'}],
        [operation('S01',1,'evaluate-condition','must','P-RULES','token available in finite supply',['SA-GEAR']),operation('S02',2,'select-target','must','P-OWNER','compatible empty slot',['SA-GEAR'],decision_ref='D-GEAR-SLOT',target_ref='T-GEAR-SLOT'),operation('S03',3,'transition-zone','must','P-RULES','gained Tactical Gear token',['SA-GEAR'],transition={'from':'tax.scaffold.supply-pool','to':'selected Tactical Gear slot'}),operation('S04',4,'remove-component','must','P-RULES','all Tactical Gear tokens on a lost Item',['SA-GEAR'],conditions=['Item is lost'])],
        {'policy':'source-limited-components','unit':'requested token','onImpossible':'if all tokens of that type are held, Character cannot gain another'}, {'kind':'persistent-slot-occupancy'}, {'policy':'one token per slot; multiple slots allowed'}, [], [], []))

    records.append(record(
        'SEM-USE-ROOM-001','Use the Room Basic Action','source-backed','action','official-primary','verbatim-structure',
        [assertion('SA-USE-ROOM','SRC-RULEBOOK','printed page 12 / Basic Actions List, page 13 / action legality, and Malfunction Room restriction',['costs','preconditions','operations'],'Use the Room costs 2 Action cards, carries Not In Combat, is unavailable when the occupied Room has a Malfunction, and may be chosen only when the selected Room effect can be resolved entirely.','docs/rules/source-extraction/rulebook-visual-obligations.json:RB-P12-V02')],
        ['term.use-the-room','term.room','icon.actionCard','icon.notInCombat'],['tax.process.action.use-room','tax.entity.spatial.room','tax.entity.component.card.action','tax.state.combat.not-in-combat'],[],
        timing('TW-USE-ROOM','tax.process.temporal.turn','during','per-selected-Use-Room'),[participant('P-PLAYER','decision-owner','tax.entity.agent.player'),participant('P-CHARACTER','actor','tax.entity.agent.character')],'must',
        [condition('C-USE-ROOM','all',[{'predicate':'Character is Not In Combat'},{'predicate':'Character occupies the Room whose effect is selected'},{'predicate':'occupied Room has no Malfunction marker'},{'predicate':'chosen Room effect is fully resolvable'}],['SA-USE-ROOM'])],
        [decision('D-USE-ROOM-PAY','P-PLAYER','player-choice',2,2,False,'owner-private-until-discard',['own Action cards in hand'])],
        [{'informationId':'I-USE-ROOM','subjectRef':'declared Room effect and paid Action card faces','audience':'public','revealTrigger':'declaration/payment','secrecy':'other hand cards remain private'}],
        [{'costId':'COST-USE-ROOM','payerRef':'P-PLAYER','resourceTermId':'icon.actionCard','quantity':2,'selectionDecisionRef':'D-USE-ROOM-PAY','transition':{'from':'tax.scaffold.zone.hand','to':'tax.scaffold.zone.discard-pile'}}],[],
        [operation('S01',1,'pay-cost','must','P-PLAYER','COST-USE-ROOM',['SA-USE-ROOM'],decision_ref='D-USE-ROOM-PAY'),operation('S02',2,'invoke-process','must','P-CHARACTER','semantic Room effect for occupied Room',['SA-USE-ROOM'])],
        {'policy':'all-or-nothing-selection','unit':'Use Room Action','onImpossible':'Action may not be selected unless the chosen Room effect resolves entirely'}, {'kind':'instantaneous-action'}, {'policy':'repeatable via separate Actions'}, [], [], []))
    use_room=records[-1]
    use_room_rb=assertion('SA-USE-ROOM-RB','SRC-RULEBOOK','printed pages 13 and 22 / Use a Room Action legality',['preconditions','operations','costs'],'Use the Room is one of the two Action-card Basic Actions and cannot be performed while the Character is in a Room with a Malfunction; resolve the selected Room effect only if it is fully resolvable.','docs/rulebooks/rulebook_text.txt:lines 4368–4375')
    use_room['sourceAssertions'].append(use_room_rb)
    use_room['operations'][1]['sourceAssertionIds'].append('SA-USE-ROOM-RB')
    use_room['timing']['recurrence']='during-player-turn-per-selected-Use-Room-before-Oxygen-loss-and-Fire-damage'

    records.append(record(
        'SEM-AUTODESTRUCTION-001','Autodestruction Procedure','source-backed','procedure','official-primary','verbatim-structure',
        [assertion('SA-AUTODESTRUCTION','SRC-RULEBOOK','printed page 38 / lines 6117–6140',['timing','operations','outcomes','duration'],'When Activated, place the Autodestruction token 5 spaces ahead of the Round marker (or beyond the last space). Reaching it destroys the Facility and ends the game; only Reactor shutdown can turn it off.','docs/rulebooks/rulebook_text.txt:lines 6117–6140')],
        ['term.autodestruction-procedure','icon.autodestruction'],['tax.process.procedure.autodestruction','tax.entity.component.token.autodestruction'],[],
        timing('TW-AUTODESTRUCTION','tax.process.procedure.autodestruction','when-triggered','per-Activation-until-removed-or-triggered'),[participant('P-RULES','rules-system')],'must',[],[],[{'informationId':'I-AUTODESTRUCTION','subjectRef':'Autodestruction token position and Facility fate','audience':'public','revealTrigger':'placement/continuous','secrecy':'none'}],[],[],
        [operation('S01',1,'place-component','must','P-RULES','Autodestruction token 5 Round spaces ahead (4 empty between) or beyond final space if insufficient',['SA-AUTODESTRUCTION']),operation('S02',2,'invoke-process','must','P-RULES','Facility destruction and End of the Game',['SA-AUTODESTRUCTION'],conditions=['Round marker reaches token or endgame reaches beyond-track token'],invoke='SEM-ENDGAME-001'),operation('S03',3,'evaluate-condition','must','P-RULES','only complete Reactor power shutdown removes/deactivates token',['SA-AUTODESTRUCTION'])],
        {'policy':'ordered-complete','unit':'Activation/trigger procedure','onImpossible':'beyond-track fallback is mandatory when fewer than 5 spaces remain'}, {'kind':'persistent-until-removed-or-triggered'}, {'policy':'one Autodestruction token/procedure state'}, [{'condition':'Autodestruction triggers','result':'Facility destroyed; all non-Escaped Characters and all Intruders die; game ends'}], [], []))

    records.append(record(
        'SEM-ROBOT-MALFUNCTION-001','Robot Malfunction effects','source-backed-with-open-question','constraint','official-primary','open-alternatives',
        [assertion('SA-ROBOT-MALFUNCTION-P22','SRC-RULEBOOK','printed page 22 / lines 4383–4391',['preconditions','operations','duration','unresolvedQuestionRefs'],'A malfunctioned Robot cannot be used and has no text/icons, but effects that only require a Robot can still be used; another Robot Malfunction placement is ignored.','docs/rulebooks/rulebook_text.txt:lines 4383–4391'),assertion('SA-ROBOT-MALFUNCTION-P37','SRC-RULEBOOK','printed page 37 / lines 6015–6022',['preconditions','operations','duration','unresolvedQuestionRefs'],'A Robot with a Malfunction has no Action and all game effects mentioning the Robot are unavailable. Tactical Gear on it may still be used; adjacent discard-Malfunction effects may remove its marker.','docs/rulebooks/rulebook_text.txt:lines 6015–6022')],
        ['icon.robot','icon.malfunction','term.tactical-gear-token'],['tax.entity.agent.robot','tax.entity.component.marker.malfunction','tax.entity.component.token.tactical-gear'],[],timing('TW-ROBOT-MALFUNCTION','tax.entity.agent.robot','when-triggered','continuous-while-Robot-has-Malfunction'),[participant('P-RULES','rules-system')],'must',[],[],[{'informationId':'I-ROBOT-MALFUNCTION','subjectRef':'Robot Malfunction and effect availability','audience':'public','revealTrigger':'continuous','secrecy':'none'}],[],[],
        [operation('S01',1,'set-state','must','Robot with Malfunction','has no Robot Action and no usable printed Robot text/icons',['SA-ROBOT-MALFUNCTION-P22','SA-ROBOT-MALFUNCTION-P37']),operation('S02',2,'resolve-open-alternative','must','P-RULES','SEM-Q-010 availability of non-Action effects that mention or only require the broken Robot',['SA-ROBOT-MALFUNCTION-P22','SA-ROBOT-MALFUNCTION-P37']),operation('S03',3,'evaluate-condition','must','P-RULES','Tactical Gear on broken Robot remains usable and adjacent discard-Malfunction effects may remove marker',['SA-ROBOT-MALFUNCTION-P22','SA-ROBOT-MALFUNCTION-P37'])],
        {'policy':'per-effect-check','unit':'Robot Action/effect attempt','onImpossible':'Robot Action/text unavailability is explicit; the equal-authority effect-availability conflict remains SEM-Q-010 with no default'}, {'kind':'persistent-while-Malfunction-present'}, {'policy':'single broken/not-broken condition'}, [], ['SEM-Q-010'], []))

    return records
